### ISSUE TITLE
Not all fingers are thumbs...

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-theme#1005]
...and not all Newspack sites are on WordPress.com

**Is your feature request related to a problem? Please describe.**
On a Newspack site, the footer contains this message:

> Proudly powered by Newspack on WordPress.com

That's certainly true for Newspack on WordPress.com customers, but not for any self-hosted Newspack sites. There are two issues with this that I can see:

1. It's just not true and, y'know, we should probably not be pretty little liars. We might end up under a gazebo!
2. Self-hosted Newspack users may do things that we may not want to be associated with, and such a message could lead people to assume it's our work and that may reflect poorly on us

**Describe the solution you'd like**
Maybe just "Newspack *by* WordPress.com"

**Describe alternatives you've considered**
1. Leave it alone because maybe it's fine?
2. Remove the ".com" bit (that one is @laurelfulford's excellent suggestion)
3. Check myself into The Radley

**Comment by kinseywilson** [comment]
Probably the simplest is to say Newspack by Automattic. I think that's consistent with how we said we were going to brand the Newspack Newsletter plugin in the Dotorg directory.
