### ISSUE TITLE
Sponsors: update data handling once plugin is updated

### ISSUE THREAD

**Issue by dkoo** [Automattic/newspack-theme#1018]
Based on [this comment](https://github.com/Automattic/newspack-theme/pull/1008#discussion_r467129929), it sounds like the Newspack Sponsors plugin could provide more/different data to promote simpler logic in the theme. Once that's done on the plugin side, we should refactor the theme logic accordingly.

**Comment by laurelfulford** [comment]
Closed with #1036.
