### ISSUE TITLE
Update VIP Coding Standard

### ISSUE THREAD

**Issue by GaryJones** [Automattic/newspack-theme#102]
**Describe the bug**
The [currently used version of VIP Coding Standards](https://github.com/Automattic/newspack-theme/blob/0a05698993dcd454865fd07040a20fafa427a3ea/composer.json#L16) is `0.4.0`. This is out of date, and is not compatible with the latest versions of WPCS.

**Expected behavior**
Please use [VIPCS 2.0](https://github.com/Automattic/VIP-Coding-Standards/releases/tag/2.0.0), which was released a few minutes ago :-)

**Comment by laurelfulford** [comment]
It looks like this has been closed with #105!
