### ISSUE TITLE
Jetpack update broke Infinite Scroll

### ISSUE THREAD

**Issue by eduardogoncalves** [Automattic/newspack-theme#1107]
**Describe the bug**
At https://newspack.pub/ and other sites using newspack with Jetpack Ininite Scroll enabled, a '%%footer%%' string is displaying on page footer, as we can see at https://newspack.pub/

**To Reproduce**
Go to Jetpack -> Writing -> Theme enhancements -> Infinite Scroll -> and check Load more posts as the reader scrolls down
![image](https://user-images.githubusercontent.com/4308648/95619407-98096480-0a3c-11eb-8ac9-8d62eec039c6.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/4308648/95618533-398fb680-0a3b-11eb-8cbb-3d6345ec4ac9.png)

**Expected behavior**
On front page displays nothing. On article's page, display next article, on archive's page display's next set of articles.

**Comment by laurelfulford** [comment]
This looks like a combination of the Jetpack update, infinite scroll and AMP. 

Infinite Scroll doesn't work when AMP is enabled, which is not something we can fix at the theme level, but there might be a way to hide this odd footer, or remove support for Infinite Scroll when AMP is enabled (I'm not entirely sure if that's possible as I imagine it, but it's worth investigating!). 

For any sites that do want to use Jetpack's Infinite Scroll and the Newspack theme, AMP will need to be disabled.

**Comment by laurelfulford** [comment]
> Infinite Scroll doesn't work when AMP is enabled

Looks like I could be wrong about this -- it's working, but in a strange way (see #1108).

I'll try to dig into this further and see if I can figure out what needs updating. In the meantime, I'd recommend either turning off AMP or Infinite Scroll.

**Comment by westonruter** [comment]
It appears that the Jetpack implementation of Infinite Scroll in AMP is broken. A user also reported the issue with Infinite Scroll in Twenty Seventeen: https://wordpress.org/support/topic/footer-on-footer-amp-page/

I'm going to look into the implementation and see if I can fix it.

**Comment by eduardogoncalves** [comment]
@laurelfulford I'll close this, as it is an issue on Jetpack. Feel free to reopen it.

**Comment by westonruter** [comment]
I just commented on https://github.com/Automattic/newspack-theme/issues/1108#issuecomment-709753736:

> Well, I gave it my best shot. I found the AMP implementation of infinite scroll to not really work as expected even in the themes it is supposed to work (Twenty Twenty and Twenty Nineteen). I drafted a pull request to start to improve the implementation, but I'm not well-versed in `amp-next-page` to be aware of all the issues: https://github.com/Automattic/jetpack/pull/17497
