### ISSUE TITLE
Build out styles for 404/no search results pages

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-theme#113]
Currently the content area of the 404 and no results pages looks like this: 

![image](https://user-images.githubusercontent.com/177561/61655249-06fd7080-ac73-11e9-83ae-e090c83602bc.png)

It needs some refining, including making the search smaller.

**Comment by philipjohn** [comment]
Could we also build in some limited customisation as well? I think a few folks have asked for this, and it would be nice to provide some limited options (such as custom message, or image. Maybe a CTA?

**Comment by laurelfulford** [comment]
This hasn't come up for a while, so I'm going to close for now but we can create a new issue if it comes up again.
