### ISSUE TITLE
Featured image position does not always work

### ISSUE THREAD

**Issue by tofraser** [Automattic/newspack-theme#1130]
**Describe the bug**
For some reason, featured image layout doesn't seem to work consistently... or in the case of this article, it doesn't work at all.

**To Reproduce**
Add a featured image, choose a different position, save... no change.
Changing the default does not impact it.

Screen capture
https://www.loom.com/share/395b582840d24cab9e7dd6409dd4e92d?from_recorder=1

**Expected behavior**
Changing positions should just work.

**Comment by laurelfulford** [comment]
Thanks for reporting this issue, @tofraser !

Do you happen to have the custom fields panel visible in the editor? We've noticed some issues with that panel being open and the JavaScript-based options in the right column (like the featured image settings, or subtitle -- see #1122). 

If yes, hiding that panel should work as a temporary work around while we address the above! If not, any other details about your setup would be appreciated: non-Newspack plugins, the OS and browser you're using, etc. Thank you!

**Comment by tofraser** [comment]
@laurelfulford thank you for the swift response!

And, YES, that fixed it as a workaround which is fine for our purposes.

Thank you!

**Comment by laurelfulford** [comment]
Yay! Thanks for confirming, @tofraser!
