### ISSUE TITLE
Show/hide sponsor info doesn't work on AMP pages

### ISSUE THREAD

**Issue by dkoo** [Automattic/newspack-theme#1145]
**Describe the bug**
When clicking the small (?) icon next to the sponsorship labels on sponsored posts and archives, the sponsor disclaimer blurb is supposed to appear like so:

<img width="333" alt="Screen Shot 2020-11-12 at 2 55 16 PM" src="https://user-images.githubusercontent.com/2230142/99000852-26b74880-24f7-11eb-88ca-057f92cc18b9.png">

This is currently working when AMP is disabled, but not when enabled. On AMP pages, clicking the (?) icon has no visible effect.

**To Reproduce**

1. Make sure that the site is in standard mode (AMP-first) or transitional mode.
2. With the Newspack Sponsors plugin active, ensure that you have at least one sponsor published.
3. Assign the sponsor to a post and category or tag.
5. View the sponsored post with AMP **disabled**. Click the (?) icon at the top of the article header and confirm that the blurb appears as in the screenshot above.
6. View the sponsored post with AMP **enabled**. Click the (?) icon and observe that nothing happens.
7. View the sponsored category or tag archive. Observe that the behavior is the same for AMP vs. non-AMP mode.

**Expected behavior**
The behavior should match in both AMP and non-AMP mode. Tested in Chrome, Firefox and Safari.

**Comment by laurelfulford** [comment]
Hey @dkoo! I'm finally looking at this on my test site, and I haven't been able to recreate it. [Here's a live site using AMP](https://localprofile.com/2020/11/05/neath-the-wreaths-new-approach-to-spreading-cheer-in-2020/) where it's also working as expected for me.

Can you provide any more details about where you're seeing this, like other plugins or settings that might be contributing to it? Or confirm if the above site also isn't working for you? Thanks!

**Comment by dkoo** [comment]
Strange, the live site you provided does work for me, so it must be related to my specific environment. I do see the markup changing as expected in dev tools, I just don't see the expected styles for `.show-info`. Since you're not able to replicate and it doesn't seem to be affecting live sites, let's put this issue on hold unless I can figure out how to reliably replicate.

**Comment by laurelfulford** [comment]
> I do see the markup changing as expected in dev tools, I just don't see the expected styles for .show-info

I wonder if there's something funky with AMP stripping out those styles when it shouldn't be? Just let me know if there's anything you'd like me to test with different plugins/settings you might be using, I'm happy to help narrow it down if I can!

**Comment by dkoo** [comment]
I ended up updated all of my installed plugins and that seems to have fixed the problem. I'm not sure which one was causing the issue (maybe Jetpack?), but I think we can attribute this to user error on my part since most Newspack sites will have plugin auto-updates enabled. Thanks, Laurel!
