### ISSUE TITLE
Next/previous article on single post pages

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-theme#1160]
**Is your feature request related to a problem? Please describe.**
A publisher has expressed an interest in having next/previous links at the end of the single post template. This could help with recirculation, even though it's a more traditional blog feature.

**Describe the solution you'd like**
A simple next and previous link at the end of each post, including the title of the next and previous posts. Example:

![Screenshot (2)](https://user-images.githubusercontent.com/136342/100606472-6b1d5380-3301-11eb-8f53-91f2d702e458.png)

**Comment by SanjayKumarMonu** [comment]
Hi,

This feature has great importance in Search Engine Optimization.

Hence, I also want to have this feature on the theme.
