### ISSUE TITLE
Footer: Add option to toggle branding

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-theme#1185]
Right now, the footer branding will appear when you have footer widgets; in some cases, publishers haven't wanted that layout, though, and it needs to be  hidden with Custom CSS.  

It would be handy to have the option to hide this branding in the Customizer.

**Comment by philipjohn** [comment]
This just tripped someone up actually. They had set the footer logo, which didn't appear. After looking at the code I added a HTML widget with a HTML comment in and it showed the logo.

**Comment by laurelfulford** [comment]
With WordPress 5.8 on the horizon, and the ability to use blocks in the widget area, there's another reason to add an option to hide this: it could be rebuilt with blocks. 

Tagging as 5.8, not because it's a 5.8 issue so much as something that could benefit 5.8's tools.
