### ISSUE TITLE
Updated Date: Flip default

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-theme#1198]
Right now, the 'Updated date' option is site-wide with a per-post option to turn it off. 

We've already had a couple requests for the opposite -- to only have it turned on on a per post basis :) This needs exploration to see if it's even feasible or if it would turn into a bit of a mess. In my mind I imagine a 'show updated date' toggle by default, and then when the customize option is enabled, to switch it to the 'hide updated date' option, but we'll have to see how that actually work.

**Comment by laurelfulford** [comment]
We've had another request for this functionality from Berkeleyside.

**Comment by doug-cityside** [comment]
We've been publishing updates to our elections post reflecting updated results. This feature would be great so that it's not shown on every post.

**Comment by allykmyta** [comment]
Another request for this functionality from EN.

**Comment by gamebits** [comment]
Noozhawk has also requested this.
