### ISSUE TITLE
Multiple avatars for multiple authors

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-theme#1255]
**Is your feature request related to a problem? Please describe.**
When CAP Guest Authors are used to assign multiple authors to a post, only one (the first) author avatar is shown.

**Describe the solution you'd like**
All author avatars should be shown.

**Describe alternatives you've considered**
We could instead choose to show no avatars, but that would be inconsistent with articles that have a single author and an avatar present.

**Additional context**
This was raised by a launched publisher

**Comment by laurelfulford** [comment]
Hi @philipjohn! The theme should be looping through the author avatars in order and placing them before the byline text. 

In my (brief) testing, it seems to be working as expected, but there might be some odd case I'm not factoring in. Can you share some more details about the site (theme used; do they have Custom CSS; confirmed both authors have avatars)?

Here's what I get in Newspack Nelson with one WP author and one guest author:

![image](https://user-images.githubusercontent.com/177561/108769777-4d314a80-750e-11eb-8152-10ae6a73e072.png)

... and with two guest authors: 

![image](https://user-images.githubusercontent.com/177561/108769947-8ff32280-750e-11eb-9dc1-a9b574a437f9.png)
