### ISSUE TITLE
Archive: Add option to show subtitle

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-theme#1266]
Add an option to show the subtitle when it exists on archive pages; default to 'false' to emulate existing behaviour.

**Comment by laurelfulford** [comment]
Closing this one for now as I honestly can't remember where it originated from, and it hasn't come up since. Can reopen/create a new issue if it's a request that comes up again.

**Comment by yogeshbeniwal** [comment]
In my opinion using subtitle on Home Page Blocks, Archives page for Categories and Tags is better than using Excerpt. Publishers use Subtitle as an extension of Title where Title is too long to fit in Search engine words limitation.
