### ISSUE TITLE
Social Links Menu: Telegram

### ISSUE THREAD

**Issue by mmprep** [Automattic/newspack-theme#1269]
Is it possible to add support of Telegram in Social Links Menu?

Right now the Telegram link (e.g. t.me/some_profile) is not recognized.
Instead of the corresponding Telegram icon, the standard link icon is shown.

**Comment by laurelfulford** [comment]
Found a previous issue with this request so I'm going to close in favour of it: https://github.com/Automattic/newspack-theme/issues/722
