### ISSUE TITLE
Sidebar: Right or left position change

### ISSUE THREAD

**Issue by mmprep** [Automattic/newspack-theme#1272]
It would be great if there was a built-in option to change the position of the sidebar, either on the right or on the left.
Right now, the sidebar is always on the right.

There are many pros and cons to any particular sidebar position, depending on your goals.

Western users, for example, read from left to right, and their attention is always more to the left side of the page, whatever the case may be. Nonprofit news organizations often have to monetize their content with ads. Therefore, if desktop ads appear on the left side of the page, they are more likely to be seen.

Discussions on the topic of sidebar placement:

https://www.problogdesign.com/blog-layout/should-a-sidebar-go-on-the-left-or-right/
https://www.webmaster-source.com/2008/02/04/right-vs-left-sidebar/

I tried swapping out the sidebar and main content -- similar to how https://www.wpbeginner.com/wp-themes/how-to-change-the-sidebar-side-in-wordpress/ describes it. Unfortunately, it didn't work for me.

Can anyone tell me how to do this with CSS? I would like the sidebar to be on the left side.
Thanks in advance.

**Comment by laurelfulford** [comment]
Hi @mmprep! 

I think the issue between the instructions on WP Beginner and this theme is that the CSS is set up a bit differently than their examples. I fiddled around with it a bit, and the following should move the sidebar from the right to the left:

```
.post-template-default .main-content,
.page-template-default .main-content,
.archive .site-main,
.search .site-main,
.blog .site-main { 
    order: 2;
}
```

I hope that helps! I'm going to close this issue as resolved, but please comment here if you run into any issues with that!

**Comment by mmprep** [comment]
Hi @laurelfulford!

Thank you so much for the invaluable hint!
It's a pleasure to get help with such specific question.
