### ISSUE TITLE
Campaigns + no AMP can cause CSS weirdness

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-theme#1282]
This issue may not be best fixed in the theme, but reporting it here to start so we have a record of it:

If you have AMP disabled, and the Campaigns plugin enabled, the Admin toolbar is not aligned at the top of the page on smaller screens. The following styles look to be the culprit:

```
html.i-amphtml-fie:not(.i-amphtml-inabox) > body, 
html.i-amphtml-singledoc:not(.i-amphtml-inabox) > body {
    position: relative !important;
}
```

This is similar to an issue that happens with the Homepage Posts blocks, when AMP adds these styles which end up reducing the space underneath the featured images:

```
.i-amphtml-layout-responsive, 
[layout="responsive"][width][height]:not(.i-amphtml-layout-responsive), 
[width][height][heights]:not([layout]):not(.i-amphtml-layout-responsive), 
[width][height][sizes]:not([layout]):not(.i-amphtml-layout-responsive) {
    display: block;
    position: relative;
}
```

**Comment by adekbadek** [comment]
https://github.com/Automattic/newspack-popups/pull/959 removes loading of AMP runtime on non-AMP pages, so this should be resolved.
