### ISSUE TITLE
Flush CSS Browser Cache on the Client-side

### ISSUE THREAD

**Issue by mmprep** [Automattic/newspack-theme#1287]
Dear developers team!

Can you please tell me how to force to clear CSS browser cache on all computers and smartphones of my users?

The thing is that in .htaccess there was the following code: `ExpiresByType text/css "access plus 1 year"`. I have made a lot of design changes at the Newspack theme, and therefore would like to flush the CSS browser cache on the client-side so that the site design is displayed correctly.

An extensive discussion of the problem can be found here -- https://stackoverflow.com/questions/118884/how-to-force-the-browser-to-reload-cached-css-and-javascript-files

One of the solutions involves adding timestamp to query string via `filemtime(get_template_directory()` -- https://redearthdesign.com/blog-general/force-browsers-to-clear-style-css-cache/

In this regard, please advise me in what Newspack theme's files the code needs to be changed?
And will this code work?

Thank you in advance.

**Comment by laurelfulford** [comment]
Hi @mmprep! 

The theme uses its current version in a similar way to the timestamp query -- you can see an example of that here: https://github.com/Automattic/newspack-theme/blob/master/newspack-theme/functions.php#L381 (the `wp_get_theme()->get( 'Version' )` part). 

If you wanted to replace that with the timestamp, you could change that value in any of the scripts/styles the theme enqueues with that (searching for `wp_get_theme()->get( 'Version' )` [should help find them all](https://github.com/Automattic/newspack-theme/search?q=%22wp_get_theme%28%29%22&type=code))

You could also bump the version number in the style.scss file you're using ([example](https://github.com/Automattic/newspack-theme/blob/master/newspack-theme/sass/style.scss#L8)), and regenerate the CSS; that will replace the `wp_get_theme()->get( 'Version' )` part that's already there with a new value, having the same effect. 

> And will this code work?

I can't guarantee that there aren't odd cases where this wouldn't work for some reason, but it's the go-to approach for WordPress and I personally don't know of any specific issues with it :) 

I'm going to close this issue but let us know if you have any questions!
