### ISSUE TITLE
When creating New Page, default to "one column wide" template

### ISSUE THREAD

**Issue by iamstevebeatty** [Automattic/newspack-theme#1324]
I believe that when most people set about to create a new page, they're not thinking the sidebar is going to be part of it. They're probably looking to use the full canvas we can make available, and that's "one column wide." 

This would only be for new pages. Posts would still use whatever the default in the customizer is. 

Alternatively, add a template default dropdown on the Customizer > Templates > Pages, like this one from Customerizer > Templates > Posts: 
![image](https://user-images.githubusercontent.com/48489469/113337881-fe858600-92ed-11eb-9828-6b7ea236371d.png)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by laurelfulford** [comment]
> Alternatively, add a template default dropdown on the Customizer > Templates > Pages, like this one from Customerizer > Templates > Posts:

I think this would be the best course of action, just so we're not changing behaviour on existing publishers.
