### ISSUE TITLE
Unwanted whitespace at top of page

### ISSUE THREAD

**Issue by dkoo** [Automattic/newspack-theme#1332]
**Describe the bug**

Sites with a Facebook pixel at the top of the markup are seeing a bit of extra whitespace at the very top of the page.

**To Reproduce**
To reproduce the behavior:

Visit [this site](https://montanafreepress.org/) in an incongito sesion to trigger the above header prompt with colored background—this makes the extra whitespace visually clear.

**Screenshots**

<img width="783" alt="Screen Shot 2021-04-16 at 5 11 34 PM" src="https://user-images.githubusercontent.com/2230142/115093205-d0e83180-9ed6-11eb-93c1-410d2bc941e5.png">

**Expected behavior**
There should be no whitespace above the red background of the above-header prompt. I suspect it has something to do with the AMP rendering, but maybe there's some CSS we can apply to eliminate the whitespace?

**Comment by sonjaleix** [comment]
@dkoo I took a close look and I can't figure out a way to minimize the whitespace. It's not caused by any height or padding/margin in the CSS that we could effect. I don't have a solution for you unfortunately.

**Comment by dkoo** [comment]
@sonjaleix It looks like we could apply `display: none` to the pixel to minimize the whitespace. According to [FB's docs](https://developers.facebook.com/docs/facebook-pixel/advanced/), it shouldn't affect how the pixel functions. Looking at the inspector for MFP, we can probably target it using an `[alt="fbpx"]` CSS selector. I'm not sure if this `alt` attribute is standard or specific to MFP's site, though.

**Comment by dkoo** [comment]
This appears to be affecting just the one site, not all Newspack sites, so closing this.
