### ISSUE TITLE
Header and footer scripts are not taken into account with Newspack Theme

### ISSUE THREAD

**Issue by abhishekpc** [Automattic/newspack-theme#1333]
**Describe the bug**
I understand that Newspack Theme has no plans to include the header and footer scripts in "Customization" option. In one of your closed bugs, you suggested using one of the header and footer scripts plugins.

I tried a few of them but the scripts are not taken into account. I wanted to use Plausible analytics along with Quantcast. It seems that scripts are simply not visible. I tried checking the source and inspect the page, emptied all possible cache but the header/footer scripts are not working.

**To Reproduce**
Use the default Newspack theme.
Use any header/footer script plugin.
Add a header or footer script.
Empty the cache.
Check to find the scripts are not taken into account.

**Expected behavior**
With the plugins, the scripts should work for stats collection or cookie monitoring.

**Comment by laurelfulford** [comment]
Hi @abhishekpc! Thanks for reporting this issue. 

I tried to recreate this by installing [Header and Footer Scripts](https://wordpress.org/plugins/header-and-footer-scripts/) and adding the script `<script src="//cdnjs.cloudflare.com/ajax/libs/velocity/2.0.6/velocity.min.js"></script>`. It seemed to work as expected for me (I could find the script when viewing the page source) but I had to disable AMP -- if you do have AMP enabled (like if you used the Newspack plugin to set up your site), AMP will be enabled by default, and it will strip out most JavaScript files on the front-end. 

Please double-check that AMP is disabled; if it is, can you please confirm:

1. Exactly what plugin you're using to add the scripts? There are a few that reference Headers and Footers, and I just want to make sure I'm trying the right one!
2. Please try with all other plugins disabled, and see if that helps weed out the issue.

Just let me know if you have any questions about the above - thanks!

**Comment by abhishekpc** [comment]
@laurelfulford Thanks for taking a look at it.

What I noticed is that the scripts used as header and footer should be AMP compatible. Google Anlaytics and some other analytics have a separate AMP scripts.

Normal scripts are simply not taken into account.

**Comment by laurelfulford** [comment]
Hi @abhishekpc! Can you please let me know what plugin you're using to insert the scripts, and specifically what JavaScript files you're trying to insert that aren't working? I'm happy to try and see if I can recreate the issue you're seeing, but so far I haven't had any luck - it's working as expected for me, but I might be a specific case I'm missing. 

Also, do you still have this issue when AMP is turned off, or when all other plugins are disabled?
