### ISSUE TITLE
Featured snippet related issues

### ISSUE THREAD

**Issue by satishvu5** [Automattic/newspack-theme#1350]
**Featured snippet related issues**
After adding Newspack theme on my site, why my sites google featured snippets results is removed? It is theme related problem?

Please also check newspack theme used other sites and their google featured snippets.

**Comment by laurelfulford** [comment]
Hi @satishvu5! 

There shouldn't be anything in the Newspack theme that is causing featured snippets not to display. 

When I tried a couple searches trying to find sites running the Newspack theme, asking questions (as opposed to just searching for the name), a featured snippet did appear for a few of them:

![image](https://user-images.githubusercontent.com/177561/122299898-6ee68100-ceb3-11eb-850c-f6519264af5e.png)

![image](https://user-images.githubusercontent.com/177561/122300176-cedd2780-ceb3-11eb-9ffe-4b5223320c02.png)

![image](https://user-images.githubusercontent.com/177561/122300373-16fc4a00-ceb4-11eb-9516-adacaecde998.png)

![image](https://user-images.githubusercontent.com/177561/122300460-309d9180-ceb4-11eb-8b0a-652e50c55940.png)


It could be something has changed on Google's side, like the criteria for a featured snippet is no longer being met - I'm far from an expert, but if you can share the site URL that is not working for you, and the search query, it could help!

**Comment by laurelfulford** [comment]
Hi @satishvu5 -- I'm going to close this issue since it doesn't seem to be theme related. Just let us know if you have any questions at all about that. Thanks!
