### ISSUE TITLE
"Cancel reply" appears to logged-out users

### ISSUE THREAD

**Issue by gamebits** [Automattic/newspack-theme#1429]
When the "Users must be registered and logged in to comment" option is enabled, and the site is using WordPress comments (not Jetpack comments), then a logged-out user may see the link to "Cancel reply", as seen at the bottom of [this story](https://hyperallergic.com/662951/interlude-residency-for-artist-parents-first-of-its-kind/):

<img width="885" alt="hypercancel" src="https://user-images.githubusercontent.com/12199101/126558242-09e895db-ccd1-434b-8c91-7141519ced22.png">

**Comment by gamebits** [comment]
We're using this CSS as a workaround:

```
#cancel-comment-reply-link {
	display:none
}
```

**Comment by laurelfulford** [comment]
This is a super weird one! It seems to be behaving erratically only with the combination of AMP + collapsed comments + comments limited to logged in users -- the `hidden` attribute that's normally added to the link (and used to hide it) isn't added to start, or it's removed when you toggle open the 'Collapsed Comments' 😕
