### ISSUE TITLE
Page Templates: providing helpful defaults

### ISSUE THREAD

**Issue by rickybanister** [Automattic/newspack-theme#148]
We have provided publishers with tons of flexibility and options, but that's not enough. In order to leverage the available functionality we need to help provide guidance. This is especially true for individual article page templates (the page of any news site that receives the most traffic). 

On individual article pages newsrooms will want advertisements, related content call outs, calls to action for subscribership, and so forth. We need to develop a solution and a template that provide placeholders for those things with smart set up states that lead publishers through set up and configuration if it hasn't already been done. 

In lay terms, our article template should have a method for pre-inserting helpful block placeholders for things like ads, related content, and membership calls to action.

**Comment by laurelfulford** [comment]
Closing this for now as it's not something we've explored specifically with this iteration of the Newspack theme. 

It's very possible it could be something we could tackle down the line using block patterns when the theme is revamped.
