### ISSUE TITLE
Hide prefixes on category archive H1 tags 

### ISSUE THREAD

**Issue by gamebits** [Automattic/newspack-theme#1493]
Category archives have an H1 tag like [this example](https://newspack.pub/category/news/):

```
<h1>
<span class="page-subtitle">Category: </span>
<span class="page-description">News</span>
</h1>
```

Some sites use CSS to hide the "Category: " prefix and/or use Yoast SEO to set the `<title>` tag as "News Archives".

But whatever the CSS or Yoast setting, Google still indexes this category title as "Category: News", which is suboptimal. How can that prefix be removed from Google's search results?

[Potentially related code](https://github.com/Automattic/newspack-theme/blob/63994993aa8a513bdaf752de4b27f44e9c4ec1b9/newspack-theme/functions.php#L974-L994).

**Comment by laurelfulford** [comment]
@gamebits I've been messing around with this a bit; I'd hoped I could just move the 'prefix' part outside of the `<h1>` but it looks like that might require redoing some of the CSS to make it look the same, which makes me a bit nervous (especially when we factor in sites with Custom CSS). 

Another approach I'm thinking is to add a theme option to hide the prefix/remove it from the markup. This comes up as a customization request often enough, it could be nice to have a toggle for it. In a similar vein, we could add some kind of option to override how the archive titles are formatted (like being able to change Category: Entertainment to Entertainment Archives). 

In both cases, though, the site will actually need to change the setting to have it be changed in the Google sitelinks; by default the prefix will still be showing up there. I'm not sure if this is sufficient, or if it's something we should try to change on all sites, without changing settings -- let me know what you think!

**Comment by gamebits** [comment]
@laurelfulford I think empowering the publisher with the options to enable/disable/edit these settings is the best possible solution. Make it so! 🖖🏻
