### ISSUE TITLE
Add support for links in subtitles

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/newspack-theme#1500]
Now that we've got support for links in the image credits, could we also add support for the `<a>` tag in Subtitles? 

Tapas / Forbes would like to add it.

**Comment by laurelfulford** [comment]
Just noting for myself that the Homepage Posts block currently escape all HTML added to this field, so on top of adding link support to the theme, we'll need to add the same support to output these in the blocks (or at least not escape them -- stripping them out entirely is better in this case!).
