### ISSUE TITLE
Remove initial-scale=1 from header viewport declaration

### ISSUE THREAD

**Issue by gamebits** [Automattic/newspack-theme#1501]
An AMP analysis of a Newspack site offered [this advice](https://developers.google.com/web/updates/2013/12/300ms-tap-delay-gone-away):

> Set viewport width to match the device width to disable touch delay, which can increase FID… This [code] sets the viewport width to the same as the device, and is generally a best-practice for mobile-optimized sites.

```
<meta name="viewport" content="width=device-width">
```

But the [Newspack theme header](https://github.com/Automattic/newspack-theme/blob/2be2c798b8c423ed5a4358ce5b652b132e1d21b9/newspack-theme/header.php#L15) already has:

```
<meta name="viewport" content="width=device-width,initial-scale=1">
```

I would think these two lines would be functionally identical, but the addition of `initial-scale=1` is apparently throwing off the validator. In fact, `initial-scale=1` is being preemptively stripped in some instances, per AMP Project issues https://github.com/ampproject/amp-wp/issues/5894 & https://github.com/ampproject/amp-wp/pull/5903 — so maybe there's something to it? 🤔

**Comment by laurelfulford** [comment]
This should be getting added from the AMP plugin; the site that we noticed this issue with is running an older version of the plugin, so the fix just isn't included there. Versions 2.1+ should automatically strip out `initial-scale=1`.

I'm going to close this issue as we'll be able to fix this by upgrading the AMP plugin instead!
