### ISSUE TITLE
Add data-hero to featured images

### ISSUE THREAD

**Issue by gamebits** [Automattic/newspack-theme#1502]
An AMP analysis of a Newspack site returned this recommendation:

> Let AMP Caches and Optimizers optimize your hero images by adding the `data-hero` [attribute](https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/amp-optimizer-guide/explainer/?format=websites#hero-image-optimization) to images in your first viewport. This can improve image loading times by up to 50%.

Is that attribute something we should add to featured images? The supplied documentation suggests it be used in the `<amp-img>` tag. 

https://github.com/Automattic/newspack-blocks/issues/861 will address adding this attribute to the top posts in the Homepage Posts block.

**Comment by laurelfulford** [comment]
Similar to https://github.com/Automattic/newspack-blocks/issues/861, after some testing we found that this attribute should be getting added by the AMP plugin; it was included in the v2.13 release. I confirmed that it's working on a test site for featured images on single posts with the latest version of the plugin (v2.14). 

I'm going to close this issue and defer to the fix in the plugin for now; once it's updated on sites, this attribute should be added automatically!
