### ISSUE TITLE
Caption width too short on mobile devices

### ISSUE THREAD

**Issue by hhugosz** [Automattic/newspack-theme#1508]
**Describe the bug**
Caption width too short on mobile devices.

**To Reproduce**
1. Go to https://comeananas.news/empresario-ligado-a-senah-organizou-curso-de-compliance-no-ministerio-da-justica/

**Screenshots**
![image](https://user-images.githubusercontent.com/69354831/132666153-de3cd523-16bc-42b8-ae9b-d2cf032a5a0f.png)

**Comment by laurelfulford** [comment]
Thanks @hhugosz! 

I can recreate this as well with centred images.

We'll look at a fix in the theme, but for the short-term, the following CSS should help:

```
@media only screen and (max-width: 599px) {
     .wp-block-image .aligncenter {
          display: table;
     }
}
```
