### ISSUE TITLE
Add support for CAP / multiple author bios

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/newspack-theme#1526]
The option to include the author bio only includes the first guest author. Since Newspack publishers often have multiple authors per post, we should include guest authors in the Author Bio options.

**Comment by laurelfulford** [comment]
Followed up on this in Slack, and closing the loop here, too: 

The Author Bios at the bottom of posts [will only show when the author has a 'Biographical Info' in their profile](https://github.com/Automattic/newspack-theme/blob/master/newspack-theme/template-parts/post/author-bio.php#L24) -- this works this way for both regular authors and Co-Authors Plus Guest authors. 

This is to avoid showing near-empty bios of photos, names and links to the archives. It can be confusing, though, especially when more than one author is assigned and only one appears... and this is compounded by [the theme also having a control to turn off bios site-wide](https://github.com/Automattic/newspack-theme/pull/462).

Closing this for now, as it's working as expected!
