### ISSUE TITLE
Remove `overflow: hidden` from the two-column template.

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-theme#1551]
The theme currently uses `overflow: hidden` to make sure full-width blocks don't cause a slight side scroll (though I'm not sure if that's even still needed - see #1530).

This is interfering with sticky ads added to the sidebar; since these pages can't have full-width blocks, the overflow should be safe to remove at least from the two-column template.

**Comment by allykmyta** [comment]
WCT is also reporting the same interference with sticky ads issue.
