### ISSUE TITLE
Featured image captions pull other text when image caption is null

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/newspack-theme#1564]
**Describe the bug**

This seems to be a conflict with Image Credits. When there is an image credit, a description but no caption, the `figcaption` for Large and Small featured images pulls in extra copy from other plugins. 

Washington City Paper (Will reported): - this is from prompts

![Screen Shot 2021-10-27 at 12 36 47](https://user-images.githubusercontent.com/22805865/139108919-20c5fbd6-ee0f-4c2b-b811-43e066dec0d7.png)

[inewsource clone](https://inewsource-debug.newspackstaging.com/) to repro: - no idea where this is coming from
![Annotation on 2021-10-27 at 15-15-55](https://user-images.githubusercontent.com/22805865/139131998-002d800f-8221-405e-9a3e-de2ddfd366a1.png)

I also saw this on Model Home and it pulled the text from the Media Partners plugin (couldn't make it happen again so no screenshot). 

**To Reproduce**

2. Create a post with a featured image that includes a **credit, a description but no caption**.
3. Make sure the featured image position is either Large or Small (the caption is displayed in the post).
4. Publish the post.
5. View the post in a browser where you are not logged in and observe the text that doesn't belong is included with the caption.
6. Go back to the image and add the caption. Update the post. 
7. Notice that the caption appears correctly when viewing the post.

**Comment by laurelfulford** [comment]
Just for my own troubleshooting, in Inewsource's case it's coming from the 'Trust Indicators' plugin -- it's the same content that's being injected at the bottom of the post content.
