### ISSUE TITLE
Mobile usability issues

### ISSUE THREAD

**Issue by yogeshbeniwal** [Automattic/newspack-theme#1591]
**Describe the bug**
Recently Google Search Console has started reporting Mobile Usability issues:
- Text too small to read
- Clickable elements too close together
- Content wider than screen

On performing deep dive using lighthouse, you can detect some of related issues:
- Tap targets are not sized appropriately: Appearing for links in footer widgets
- Background and foreground colors do not have a sufficient contrast ratio: Tags at the bottom of post

**To Reproduce**
1. Go to search console and check for mobile usability issue
2. Perform a deep dive on elements causing issues using Lighthouse

**Expected behavior**
- Website using the theme should be detected as mobile friendly in search console with no error

**Comment by laurelfulford** [comment]
Thanks for reporting this, @yogeshbeniwal!

> Background and foreground colors do not have a sufficient contrast ratio: Tags at the bottom of post

For this issue, could you please share the settings on the site when this happened -- specifically the child theme and custom colours? I'm having a hard time replicating this but I think it's just the settings I'm using. Thank you!

**Comment by yogeshbeniwal** [comment]
@laurelfulford Using Newspack theme with below color settings:

Primary custom color: #3366ff
Secondar custom color: #0070d9
background color to the footer: #f8f9fa

**Comment by laurelfulford** [comment]
@yogeshbeniwal thank you! I'm getting it with those settings as well -- spinning up a fix for that!

**Comment by laurelfulford** [comment]
The tag contrast issue should be resolved with #1693; I realize the core issue mentioned (Google Search Console reported mobile issues) may not be fully addressed by that PR and #1692, but I think it'll be easiest to track and test any additional specific issues that may come up in their own tickets!

**Comment by yogeshbeniwal** [comment]
Thanks @laurelfulford. Yes, Its difficult to identify exact cause of Mobile Usability issues. Most closest guess I can make it, this may be because of Automattic/newspack-ads#236.

**Comment by yogeshbeniwal** [comment]
@laurelfulford A quick update on this, As we guessed, Pages are still reported with mobile usability issue.
