### ISSUE TITLE
Add a class or ID to the main-content <div> or <main> related to the template that's being used

### ISSUE THREAD

**Issue by earcos** [Automattic/newspack-theme#1595]
**Is your feature request related to a problem? Please describe.**
There isn't a way to add or remove or modify items via CSS based on the template a post is using (default, one column, one column wide)

**Describe the solution you'd like**
A simple but effective way, is to add a class or ID to the main-content <div> that describes the template that's being used. 

**Describe alternatives you've considered**
Since there is no way I can identify which template the post is being used from a CSS point of view, there is no alternative.

**Comment by earcos** [comment]
Nevermind. `.has-sidebar` and `.no-sidebar` did the trick 😊

**Comment by earcos** [comment]
Sorry. Reopening this again since the theme uses the `.has-sidebar` class even if the `<aside>` tag is hidden. It seems it depends on whatever the `<aside>` widgets area is populated or not. Nothing to do with the sidebar being displayed or not depending on which theme is chosen on a post.

**Comment by laurelfulford** [comment]
Hi @earcos! 

> Reopening this again since the theme uses the `.has-sidebar` class even if the `<aside>` tag is hidden. It seems it depends on whatever the `<aside>` widgets area is populated or not. Nothing to do with the sidebar being displayed or not depending on which template is chosen on a post.

Ah that's a good catch! I have a feeling that predates the theme actually having the different templates it does now :) 

In the meantime, the `body` tag should have a CSS class on posts and pages based on what template is assigned; they're generated dynamically by WordPress, so they're a bit different based on page type, but they are:

Default:
`.post-template-default`
`.page-template-default`

One-Column:
`.post-template-single-feature`
`.page-template-single-feature`

One-Column Wide: 
`.post-template-single-wide`
`.page-template-single-wide`

Will this work for now for what you're trying to do?

**Comment by earcos** [comment]
Laurel, this works amazing. Thanks a lot.

**Comment by laurelfulford** [comment]
Awesome, @earcos! 

The `has-sidebar` and `no-sidebar` classes should also be working as expected in the release after next, thanks to your report! Once fixed, they should work the same as those body classes, except they'll also factor in the [different archive page settings](https://newspack.pub/support/themes/archive-settings/#archive-layout) (for example, if you pick one of the one-column layouts in the Customizer, you should get the `no-sidebar` class on those pages, too!).

**Comment by earcos** [comment]
I'm so glad to read that! Thank a lot for everything 😊 and a pleasure to help.
