### ISSUE TITLE
Are you guys planning to make Newspack into a Block-Based Theme?

### ISSUE THREAD

**Issue by SanjayKumarMonu** [Automattic/newspack-theme#1649]
WordPress 5.9 is all set to release on January 25, 2022.

This is the first release when _WordPress is supporting "Block-Based Theme" in its core_ (I mean not by using the Gutenberg Plugin).

So, my question is, Do you guys consider converting Newspack Theme into a Block-Based theme?

**Comment by laurelfulford** [comment]
Hi @SanjayKumarMonu! 

We do not plan to change this exact theme into a block-based theme -- trying to modify it in that way without changing how existing sites look and act won't be easy to do. 

We have discussed developing a new theme for Newspack that does support full-site editing, but that's in early stages still -- there aren't any specifics to share publicly yet. 

Hope this helps!
