### ISSUE TITLE
Button block: `!important` in WP 5.9+ CSS variables overrides hover styles

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-theme#1713]
**Describe the bug**
As of WP 5.9, the block CSS includes an `!important` when assigning preset background colours:

```
.has-white-background-color {
    background-color: var(--wp--preset--color--white) !important;
}
```

Because the theme also uses the `.has-white-background-color` in its baked in colours, this ends up getting used, and for the Button block, it overrides the default dark hover background. Instead of having white text on a dark background on hover, you get white text on a still-white background.

**To Reproduce**
1. Add a button block to a post; give the button a white background and black text.
2. Publish.
3. Hover over the button block.

**Screenshots**
Button with white background:

![image](https://user-images.githubusercontent.com/177561/154772621-41f46941-4e83-4daf-8f34-0056dd9e8aba.png)

Button with white background on hover:

![image](https://user-images.githubusercontent.com/177561/154772665-86070021-4d03-47cf-b4d8-0c4d63b7f674.png)

**Expected behavior**

Correct button hover colours -- white text, and the correct `#111` background:

![image](https://user-images.githubusercontent.com/177561/154772704-285eb70a-3a47-4554-b099-18eb0dd8ae6a.png)

**Comment by 9ete** [comment]
@laurelfulford fix pushed, please let me know if you would like it resolved in a different way.
