### ISSUE TITLE
AMP javascript loading on non-amp page

### ISSUE THREAD

**Issue by yogeshbeniwal** [Automattic/newspack-theme#1767]
**Describe the bug**
Multiple AMP javascripts (shown in screenshot below) are loaded on non-AMP page. Can save few bytes for performance as these are not required.

![Screen Shot](https://user-images.githubusercontent.com/7325107/163657412-2904ebee-6cf7-4203-a315-dfffaee765ae.png)

**Comment by laurelfulford** [comment]
@yogeshbeniwal In my testing, I can't recreate this with just the Newspack theme + AMP plugin + AMP off on a page/post -- they do show up when I activate the Newspack Campaigns plugin though.

Can you confirm if this is what you're seeing too? If yes, [it looks like a similar issue was reported there and closed](https://github.com/Automattic/newspack-popups/issues/193) based on other AMP-related work being done. If no, and you are seeing this issue with just the theme and AMP plugin, can you please let me know? Thanks!

**Comment by yogeshbeniwal** [comment]
@laurelfulford Yes, it is after Campaign plugin is activated. As this will tackled in that repo, closing here.
