### ISSUE TITLE
Reader View

### ISSUE THREAD

**Issue by mmprep** [Automattic/newspack-theme#1768]
For many sites running Newspack and viewed in Reader View (Reading Mode) in the Safari browser, tags and authors disappear at the bottom of posts.

Examples:

https://mbu.ug/2022/04/15/former-uma-administrator-walter-walusimbi-bedridden-battling-heart-complications/
https://buckrail.com/chamber-to-review-old-west-days-parade/
https://www.washingtoninformer.com/trayon-white-claims-win-in-challenge-to-mayoral-petition/

**Comment by laurelfulford** [comment]
To me, this seems to make sense -- the tags and author bio aren't exactly part of the story, and this seems to line up with other news sites I've tested (at least the author part! I haven't spotted any others with tags yet 🤔 It's also removing the category from the top of Newspack sites, and this does line up with similar content on other news sites). 

It does look like the markup structure is contributing in part to what Reader is showing - moving both the tags and author inside of the [`entry-content` div](https://github.com/Automattic/newspack-theme/blob/master/newspack-theme/template-parts/content/content-single.php#L32-L67) gets at least part of author bio showing (name and text; no social or links). If it's truncated, it just trails off with no link; the tags still don't show at all: 

![image](https://user-images.githubusercontent.com/177561/164054555-c767b11d-07a5-476c-8644-3095005f25d0.png)

That being said, I'm a little leery about making changes to the markup like this unless it's totally necessary -- it could have unexpected negative consequences on live sites. 

Factoring in all of the above -- that these elements aren't part of the story, that the bio can be cut off, and that getting it to show will require changing the HTML structure of the story -- I'm going to close this issue as 'wontfix'. But please let me know if you have any questions at all about the above, and if this does continue to come up I can reopen!
