### ISSUE TITLE
Centred logo not truely centred

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-theme#178]
When the logo is centred but the header isn't 'short', the logo isn't actually in the middle.

This setting also has some other visual weirdness (screenshots to come).

**Comment by laurelfulford** [comment]
The logo should line up with the menu below it, but doesn't:

![image](https://user-images.githubusercontent.com/177561/62803573-a7d79280-ba9f-11e9-8430-b9399cf1fd48.png)

**Comment by jeffersonrabb** [comment]
Some examples:

<img width="1727" alt="Screen Shot 2019-08-09 at 3 59 02 PM" src="https://user-images.githubusercontent.com/1477002/62805812-18da7280-babf-11e9-8373-05244313d90d.png">

<img width="1727" alt="Screen Shot 2019-08-09 at 4 01 17 PM" src="https://user-images.githubusercontent.com/1477002/62805821-1e37bd00-babf-11e9-9dd9-7e0654ff31dc.png">
