### ISSUE TITLE
CSS Classes: swap out `is_page_template` check

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-theme#1811]
Right now, [the theme checks if a template -- any template -- is assigned](https://github.com/Automattic/newspack-theme/blob/master/newspack-theme/inc/template-functions.php#L153) before deciding whether to add a `no-sidebar` or `has-sidebar` CSS class to the `body`. 

We've recently had a site migrate over from WordPress where the template information on posts came with it, causing this check to return `no-sidebar` even though the default template was assigned. 

We fixed this by running  a script to remove non-NP templates from the posts, but as a precaution going forward it seems to make sense to update this check to look for the specific two possible custom templates in the Newspack theme, instead of any template in general.

**Comment by gamebits** [comment]
More details in Slack: p1652813388839829-slack-C01C378QWRX

**Comment by gamebits** [comment]
Additional context: Getting the theme to ignore any non-standard page templates would be preferable to what we did here (running a script to remove those template references). In some migrations, those non-standard templates may indicate content that needs to be transformed in a particular way; a script such as the one we ran eliminates that context.
