### ISSUE TITLE
Top Posts & Pages: increase image size and review styles

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-theme#1830]
**Is your feature request related to a problem? Please describe.**
We have a few pubs using Jetpack's Top Posts & Pages widget/shortcode. It's still using the default image size (40px x 40px) but it would be nice to increase that to something that's easier to see/more comparable with how the Homepage Posts block can be styled.

The styles should also be reviewed for when this is added as a widget or shortcode, with and without AMP, to make sure things are styled consistently (in some cases the posts appear with their list markup). 

Related docs: https://jetpack.com/blog/custom-thumbnails-top-posts-widget/

**Comment by gamebits** [comment]
Context in p1673979364725539-slack-C01C378QWRX
