### ISSUE TITLE
Fonts: Move default Google Fonts into themes

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-theme#1856]
**Is your feature request related to a problem? Please describe.**
Currently most of the Newspack themes (excluding the parent themes) load Google Fonts from fonts.google.com.

Copies of the default font options should be moved to the themes instead, to comply with the GDPR. 

See: https://make.wordpress.org/themes/2022/06/18/complying-with-gdpr-when-using-google-fonts

**Comment by yogeshbeniwal** [comment]
@laurelfulford Using custom font by site admins will still make it GDPR non-compliant. Can we extend this issue to also download custom selected webfonts and host them locally, please see [webfont-loader](https://github.com/WPTT/webfont-loader).

**Comment by laurelfulford** [comment]
Thanks @yogeshbeniwal! That is on our radar -- the goal for the near-term was just to have a non-Google default for each of the themes. 

If you'd like to host webfonts locally to use on a site, the approach we've been using has been to SFTP the font files into to the `/uploads` folder, and then making them available on the site using `@font-face` in the Custom CSS.
