### ISSUE TITLE
Option to hide primary menu from Slide-out Sidebar and Mobile Menu

### ISSUE THREAD

**Issue by yogeshbeniwal** [Automattic/newspack-theme#1869]
**Is your feature request related to a problem? Please describe.**
Primary menu is added to Slide-out Sidebar with Simple header on subpages and Mobile Menu. Primary menu generally have items with drop down, this create indentation on subpages and Mobile Menu. 

**Describe the solution you'd like**
Option to hide Primary menu while using Slide-out Sidebar with Simple header on subpages and Mobile Menu. Key categories added to Slide-out Sidebar are enough for users to navigate website and hence Primary menu is not required to be added.

**Comment by laurelfulford** [comment]
Hi @yogeshbeniwal! 

I think the best bet for something like this would be to use Custom CSS, since the requirement sounds like it's tied to how a site's navigation is set up. I haven't run into a case where it made sense to hide the Primary Menu like this on any sites I've worked with, but I have hidden things in the Slideout Sidebar and Mobile Menu before. It's just so specific to how a site's navigation is designed, adding toggles for every option gets more confusing than helpful. 

This CSS would hide the Primary Menu in the Slideout Sidebar + Simplified Header and in the Mobile Menu, plus remove the space and border from the menu/widget that follows them:

```
.subpage-sidebar nav.main-navigation,
.mobile-sidebar nav.main-navigation {
	display: none;
}

.subpage-sidebar nav.main-navigation + *,
.mobile-sidebar nav.main-navigation + * {
	border: 0;
	padding-top: 0;
}
```

Please let me know if you have any questions at all -- thanks!

**Comment by yogeshbeniwal** [comment]
@laurelfulford  Thank you. I may have all cool CSS tricks from our past discussions so far.

Above CSS works fine to hide primary menu, but it also add an error in browser console.

`
[Action] Target "mobile-sidebar" not found for action [tap:mobile-sidebar.toggle].
`

**Comment by laurelfulford** [comment]
Hi @yogeshbeniwal! I can't recreate this issue, and I'm not sure how CSS alone could trigger it -- can you please share some more information about your exact menu and header set up, and any other details you think might be relevant (like non-standard Newspack plugins or code?). Also, are you using regular AMP, Transitional AMP or AMP Plus? 

By default, the theme will always output the mobile-sidebar container (basically [all of this code](https://github.com/Automattic/newspack-theme/blob/master/newspack-theme/template-parts/header/mobile-sidebar.php)) whether or not the mobile menu is populated -- it's the bit that has the "mobile-sidebar" target the error mentions.  

The mobile menu toggle only appears in certain cases -- the theme [includes a check to make sure menus are actually assigned](https://github.com/Automattic/newspack-theme/blob/master/newspack-theme/header.php#L76-L81) before outputting the mobile menu toggle that has that `tap:mobile-sidebar.toggle` action assigned. The <a href="https://github.com/Automattic/newspack-theme/blob/984644407faa7b30acc38752f2cfbac971cb4f3b/newspack-theme/inc/template-tags.php#L529-L537">`newspack_has_menus()`</a> function specifically checks whether the site either has a primary, secondary or tertiary menu assigned, OR has the slide-out sidebar turned on, populated, and set to display on mobile.

One other thing that could be helpful to check is to view source and see if your mobile sidebar has the ID `mobile-sidebar` or `mobile-sidebar-fallback`. 

Thanks!

**Comment by yogeshbeniwal** [comment]
@laurelfulford Domain affected is www.theaccsense.com

**Comment by yogeshbeniwal** [comment]
> but I can't recreate it with options like transitional AMP, or AMP Plus.

AMP is completely disabled and not used anymore.

> can you confirm whether it does stop when it's removed?

Console error is still shown even after removing CSS.
