### ISSUE TITLE
Single posts option to show excerpt in place of subtitle

### ISSUE THREAD

**Issue by gamebits** [Automattic/newspack-theme#1890]
**Is your feature request related to a problem? Please describe.**
The Newspack Themes include a field where you can add a [subtitle](https://newspack.pub/support/themes/posts/subtitles/), or dek, to your posts. This subtitle will be displayed with the title on single posts, or can optionally be displayed with a post when using the [Homepage Posts block](https://newspack.pub/support/blocks/homepage-posts/#post-control-settings).

Some publishers use identical content in the subtitle and excerpt fields. They can't rely on just one:

* If a publisher uses the excerpt field exclusively, then it will show up in the Homepage Posts block and on archive pages, but not above single posts' featured images.
* If a publisher uses the subtitle field exclusively, then it will show up in the Homepage Posts block and above single posts' featured images, but not on archive pages.

To encompass all these use case scenarios, publishers need to duplicate the content into both fields, which seems an unnecessary redundancy.

**Describe the solution you'd like**
If the theme had a single posts content template option to "Show excerpt instead of subtitle", then publishers could use the excerpt field exclusively.

**Describe alternatives you've considered**
As part of a publisher's migration to our platform, we've created a command to duplicate their existing excerpts into subtitles: https://github.com/Automattic/newspack-custom-content-migrator/pull/188

However, this doesn't address their workflow for future content, which may still require manual duplication of content. Resolving this issue may even eliminate the need to run that migration command at all.

**Additional context**
Both Noozhawk and Berkeleyside would benefit from this feature.

**Comment by laurelfulford** [comment]
This has come up again from The Assembly -- they would like the same content displayed at the top of single posts, and with their archives.

**Comment by tmmbecker** [comment]
Barry at LakelandNow asked about this too.

**Comment by gamebits** [comment]
Injustice Watch would also need this.

**Comment by gamebits** [comment]
Now also in Asana: 1200550061930446-as-1205502642122803
