### ISSUE TITLE
The 1 side-effect

### ISSUE THREAD

**Issue by szepeviktor** [Automattic/newspack-theme#194]
This is a very-well written theme.
All of its code - except adding hooks - has no [side-effects](https://www.php-fig.org/psr/psr-1/#23-side-effects).

There is one exception: https://github.com/Automattic/newspack-theme/blob/master/inc/style-packs.php#L7

Could you make it an add_filter or add_action?

**Comment by claudiulodro** [comment]
If I understand what you're saying correctly, something roughly like this should work?

in `style-packs.php`:
```
function newspack_initialize_style_pack(){
    return new Newspack_Style_Packs_Core(
        {...}
    );
}
add_action('init', 'newspack_initialize_style_pack');
```

**Comment by szepeviktor** [comment]
Yes!

**Comment by laurelfulford** [comment]
I'm going to close this issue as the style packs were eventually reworked to be child themes, so this function no longer exists.
