### ISSUE TITLE
ARIA IDs are not unique

### ISSUE THREAD

**Issue by estereofonico** [Automattic/newspack-theme#1963]
Pagespeed and Lighthouse reports have recently changed. 

In the latest report we get, we see this issue as a problem for the SEO of my URLs. 

According to this report: The value of an ARIA ID must be unique to prevent other instances from being overlooked by assistive technologies.

This issue is related to the submenu items on the menu. 

`<html>`
`<body>`
`<!--StartFragment-->`

Failing Elements
--
nav.main-navigation > ul#menu-principal > li#menu-item-408 > ul#submenu-408
`<ul class="sub-menu" id="submenu-408">`
CineSeriesDisney+Star+HBO MaxNetflixParamount+
`<ul class="sub-menu" id="submenu-408">`

`<!--EndFragment-->`
`</body>`
`</html>`

Could you please try to solve this? 

Thanks for your help.

**Comment by laurelfulford** [comment]
Thanks @estereofonico! 

This looks to be due to the mobile menu; the IDs were originally added to match the dropdown menus with their toggles, so shouldn't be needed in the mobile menu at all.
