### ISSUE TITLE
Buttons do not have an accessible name

### ISSUE THREAD

**Issue by deLisle** [Automattic/newspack-theme#1991]
**Describe the bug**
PageSpeed and Lighthouse complain on the desktop version on menus that have sub items. It's the arrow button that doesn't have an accessible name.

**To Reproduce**
If you run pagespeed on a site that has a menu with sub items you'll see the issue under Accessibility for the Desktop version.

**Screenshots**
<img width="931" alt="Screenshot 2022-12-02 at 09 32 06" src="https://user-images.githubusercontent.com/195763/205250960-1e9dba57-6f52-4f7b-9085-0b53f2a1b763.png">

**Expected behavior**
For it to work properly read more here: https://dequeuniversity.com/rules/axe/4.4/button-name?utm_source=lighthouse&utm_medium=lr

**Comment by laurelfulford** [comment]
This should be resolved in #2025!
