### ISSUE TITLE
Hide Category Description

### ISSUE THREAD

**Issue by khabarsatta** [Automattic/newspack-theme#2206]
**Describe the issue**
Showing Category Description. I want to hide category description can you please tell me how can i hide

**To Reproduce**
Category Link : [Seoni News](https://khabarsatta.com/seoni-news)

**Screenshots**
![Screenshot_2023-11-20-13-41-26-50_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Automattic/newspack-theme/assets/64256639/4c61a461-e560-4b78-b381-cc8187733aca)

**Expected behavior**

**Comment by laurelfulford** [comment]
Hi @khabarsatta! There isn't an option to hide the archive description, but you can hide it by copy-pasting the following CSS into the Additional CSS field in the Customizer: 

```
.archive .taxonomy-description {
    display: none;
}
```

This will hide it for all of the archives; if you just want to hide it for one, each archive should have a unique CSS class that uses the category/tag's slug on the `<body>`-- so if you just wanted to hide it on that one archive, you could add the CSS class for the Seoni News category: 

```
.category-seoni-news.archive .taxonomy-description {
    display: none;
}
```

I'm going to close this issue as resolved, but please let me know if you have any questions!
