### ISSUE TITLE
Search Block: needs styles to match the search widget

### ISSUE THREAD

**Issue by rickybanister** [Automattic/newspack-theme#285]
Adding a search block to a page or column displays this:

![image](https://user-images.githubusercontent.com/437258/63365622-fc073000-c345-11e9-9e9d-5f3c73b7b7bb.png)

It'd be great to style that to match the search widget or search's appearance in the navigation.

**Comment by laurelfulford** [comment]
Hm, it doesn't look like we'll quite be able to match the theme's search box, which uses an icon for the button, and hides the text -- the search block lets you customize the search label.

I think if we can at least a) always keep the search on one line (don't wrap the button), and b) get the label matching the appearance of the 'accent' headers. I'm still not exactly sure how the button should look, though.

**Comment by rickybanister** [comment]
yeah, that's all fair!

**Comment by laurelfulford** [comment]
It looks like the search-all-on-one-line part of this has been resolved, but the custom fonts and button style aren't lining up in the editor vs the front end.

**Comment by laurelfulford** [comment]
Finally done in this PR, thanks to updates to the search block.

https://github.com/Automattic/newspack-theme/pull/1425
