### ISSUE TITLE
Menu: Two column menu

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-theme#349]
Came in from feedback:

What's the best way to handle 20+ menu items?

> We do it manually, but we can’t find an easy to use option.
>
> Today we have 20 categories, usually media have a lot. So we think the bets option is to have a faceted navigation menu like the one here in the picture:

![image](https://user-images.githubusercontent.com/177561/63893035-f6d95f00-c99d-11e9-88bd-508d385de9ca.png)

![image](https://user-images.githubusercontent.com/177561/63893074-0fe21000-c99e-11e9-85ed-a689e96a7db6.png)

Mobile: 
![image](https://user-images.githubusercontent.com/177561/63893079-17091e00-c99e-11e9-90e4-ab1e2b8b3e8a.png)

> This will allow us to show every category on the sute in our menu, plus some widgets and other cool stuff. 
>
> There are some plugins to do this. Is a tool you are considering for Newspack?

**Comment by claudiulodro** [comment]
In my experience with analytics tracking these sorts of menus, the more menu items there are the less the menu gets used in general. On giant menus like the ones pictured, there is less than 1% click-through rate for all items in the menu put together. It's just too overwhelming for users and nobody reads through the whole thing.

**Comment by laurelfulford** [comment]
Closing this one for now; I'd like us to try to handle more complex navigation structures first by page hierarchy (have higher-level menu items that drill down to pages that break down the categories more), or perhaps plugins, before we build this into the theme.

If this ends up being a higher-demand ask down the road, we can always reopen.
