### ISSUE TITLE
Native Podcast Support

### ISSUE THREAD

**Issue by luizeof** [Automattic/newspack-theme#358]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**

A native way to deliver a podcast feed along with site-specific blocks with players, playlists, and series.

**Describe alternatives you've considered**

This is a simple alternative.
https://wordpress.org/plugins/seriously-simple-podcasting/

**Additional context**

**Comment by laurelfulford** [comment]
I'm going to close this as a theme issue, as any work we've done related for Podcasts so far in Newspack has been handled in separate plugins.
