### ISSUE TITLE
Can't Install it due to error

### ISSUE THREAD

**Issue by techengage** [Automattic/newspack-theme#403]
Hi Team,

I am trying to install it on a demo site for testing purposes, but the theme is throwing an error. Stylesheet is missing. 

What should i do now?

**Comment by laurelfulford** [comment]
Hi @techengage! 

How are you trying to install the theme?

If you're cloning or downloading a zip of the master branch, you'll need to run the build process to generate the CSS from the Sass files-- there's some more details for that here:

https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md#development-workflow

We're also adding releases to https://github.com/Automattic/newspack-theme/releases -- if you download the theme from there, it will include the generated CSS. 

Just let us know if this doesn't resolve things for you -- thanks!

**Comment by techengage** [comment]
Thanks a lot. It's done.
