### ISSUE TITLE
Full Width?

### ISSUE THREAD

**Issue by techengage** [Automattic/newspack-theme#404]
Can we use the full-width page template in Style 2 inside pages? Actually, on some pages, I want to remove sidebar.

Thanks

**Comment by laurelfulford** [comment]
Hi @techengage! 

We resolved this in a recent PR; I just bundled up a new release (1.0.0-alpha.6) so it can be downloaded. If you use that version, you should have options for a one column template (with a 780px wide content area) and a one column wide template (with a 1200px wide content area) on both posts and pages. 

I'm going to close this issue, but if you run into any problems, just let us know -- thanks!
