### ISSUE TITLE
Add option to hide author bio

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-theme#433]
Right now the author bio shows if you have an author description entered.

Let's also add an option to hide it site-wide, for sites that want to have that info -- and show it on archive pages -- but don't want that bio popping up everywhere.

**Comment by producer-terry-turner** [comment]
It also displays the email address of the author, which should also be optional. Hoping this is something you could look at...?

**Comment by laurelfulford** [comment]
That's a good point, @producer-terry-turner! 

I'm going to start with a full on/off switch, and then once that's been merged, add an option to hide the email, too -- it's not information you can just leave out of your WordPress profile, so being able to turn it off would be handy!

**Comment by producer-terry-turner** [comment]
Thanks, @laurelfulford ... that will be a great addition particularly where journalists may not wih their direct email to be accessible to everyone (particularly from a spam harvesting perspective).
