### ISSUE TITLE
Style 2 Issues

### ISSUE THREAD

**Issue by WPArena** [Automattic/newspack-theme#436]
Style 2 is creating an issue. Hide Date is not working. Category Backgrounds are missing. Several more issues.

Further, can we align Blog Featured Image on Home Page full size?

**Comment by laurelfulford** [comment]
Thanks for filing this issue, @WPArena!

> Hide Date is not working.

This definitely sounds like a bug -- can you please confirm if this is only happening with Style 2? 

> Category Backgrounds are missing.

To be honest, I'm not familiar with this :) Is it a plugin, or certain core functionality that the theme could support? 

> Further, can we align Blog Featured Image on Home Page full size?

Just to make sure I understand: do you mean make the featured images the same width as the content when they're displayed on the blog posts page? 

Any additional information you could provide would be a big help -- thanks!

**Comment by WPArena** [comment]
Hi Laurelfulfod,
 
> > Hide Date is not working.
> 
> This definitely sounds like a bug -- can you please confirm if this is only happening with Style 2?

Yes, It's not working on style 2 only. 
> 
> > Category Backgrounds are missing.
> 
> To be honest, I'm not familiar with this :) Is it a plugin, or certain core functionality that the theme could support?
> 
Sorry, I would like to say Category Background Color on Style 2 isn't working.

> > Further, can we align Blog Featured Image on Home Page full size?
> 
> Just to make sure I understand: do you mean make the featured images the same width as the content when they're displayed on the blog posts page?
> 
Exactly. 

In the recent release, there is a new feature called "Beside Title Featured Image" that is also breaking style on home page by removing margin between first post and menu. 
> Any additional information you could provide would be a big help -- thanks!
I am using this theme and I will keep it testing. 

Can I get a beta entry? Anything will be much more useful.

Thank you

**Comment by WPArena** [comment]
I would also like to make the social media icons to open links in new tabs. 
Option to align Title on Full-Width Column pages. Like It looks bad when the title is left aligned and it's full-width.
A Universal Option to display featured image below the title whatever the size of the image is. Currently, it displays in two sizes if bigger it will become full size, which sometimes doesn't seem good.

Jetpack Related Posts are not looking cool on the default style. Isn't there any other option?

Option to rewrite footer credits text.

Option to select a menu for footer bottom right.

There are a lot of recommendations, fixes that I will keep posting time by time.

**Comment by laurelfulford** [comment]
Thanks for the additional information, @WPArena!

> Hide Date is not working.

Thanks for confirming that this is Style 2 only; I'll look into it! 

> Sorry, I would like to say Category Background Color on Style 2 isn't working.

Ah, thanks! Style 2 should not have a background colour on the categories, it should look like this: 

![image](https://user-images.githubusercontent.com/177561/66140298-bb423e00-e5b6-11e9-9260-33ed85f0ad4a.png)

There is an issue with the Customizer preview (#174) that makes it look like the categories will have a background on single posts, but what you see on the front-end is correct. 

> In the recent release, there is a new feature called "Beside Title Featured Image" that is also breaking style on home page by removing margin between first post and menu.

Ah, thank you! I've made a PR to fix this in #451.

> Can I get a beta entry? 

Newspack doesn't exactly have a beta; we're working with a small group of publications for our initial development, and then widening that to a larger group of newsrooms that have signed up. There's some more information about the whole development process here: 

https://newspack.blog/

I'm going to move the other items you mentioned to separate tickets -- I worry that trying to address everything in this one thread is going to get confusing, and that I'll miss something!

**Comment by laurelfulford** [comment]
I moved the new requests to separate tickets (listed above), but I realized I missed this from the original issue:

>> Just to make sure I understand: do you mean make the featured images the same width as the content when they're displayed on the blog posts page?
> Exactly.

This theme is meant to be used with the 'Article' block we're building in https://github.com/automattic/newspack-blocks. It lets you use a static front page, and using the custom blocks and Gutenberg's core ones, build a news-like front page. Because of that, the blog posts page was styled to be really simple on purpose.

**Comment by WPArena** [comment]
> > Can I get a beta entry?
> 
> Newspack doesn't exactly have a beta; we're working with a small group of publications for our initial development, and then widening that to a larger group of newsrooms that have signed up. There's some more information about the whole development process here:
> 
> https://newspack.blog/
> 
Hi Laurel,

I would like to be a part of this small development group if it's possible right now as I think I missed the deadline. I have a news publication website called [techengage.com]([url](https://techengage.com)) and I want a solid solution and your's team response is awesome. Please let me know if that's possible.

Thanks again,
Jazib

**Comment by laurelfulford** [comment]
Hi Jazib, 

Everything we're developing as part of Newspack is open source -- like the theme, the  primary [Newspack plugin](https://github.com/Automattic/newspack-plugin) (that helps tie together the features and third-party plugins we recommend), and [Newspack Blocks](https://github.com/Automattic/newspack-blocks) (a growing collection of news-focused Gutenberg blocks). 

Although we won't be able to accommodate everything, we do welcome contributions to any of these -- you might have read this already, but here are the [contribution guidelines](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md) for the theme; they're very similar for the two plugins as well.

In these earlier stages of development we've been just working with a small group of publications, but it would be cool to get perspectives outside of that!

**Comment by laurelfulford** [comment]
It looks like the issues listed in this ticket have been moved to separate tickets, and the 'Hide Date' not working should be taken care of in #904, so I'm going to close this one.
