### ISSUE TITLE
Featured Image Position Changes Don't Stick

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-theme#484]
The first time the Featured Image Position is changed works as expected. After saving the post, if you try to change the setting again and resave, the value reverts to where it was last after refreshing the page. 

**To Reproduce**
1. Create a post, set/upload a featured image.
2. Check "Behind article title" under "Featured Image Position."
3. Save or Publish the Post. 
4. Check "Default" under "Featured Image Position."
5. Save the post and refresh the page. 
6. Observe that the value reverts to "Behind article title."

**Expected behavior**
Changes to Featured Image Position to persist normally.

**Comment by laurelfulford** [comment]
@jeffersonrabb I'm not able to recreate this one -- on existing posts and new posts, switching to the behind position, publishing it and trying to switch back to default, it stays for me (both when I refresh the editor, and when I exit out of the editor and back into it). 

Can you still see this? If yes, can you drop your browser details in here, and maybe any JS errors (assuming there are some)? I tested in both Firefox and Chrome, but there might be a specific situation I'm missing. Thanks!

**Comment by laurelfulford** [comment]
Since we haven't had further reports of this issue, I'm going to close this ticket, but if it comes up again, it can be reopened :)

**Comment by jeffersonrabb** [comment]
@laurelfulford I suspect this is the same as https://github.com/Automattic/newspack-popups/issues/25. If Custom Fields are shown on a post, sidebar implementations that change them don't work. Could you quickly verify that the issue is reproducible with Custom Fields visible? If it is, we can close it with confidence and explore the issue as a possible Gutenberg problem.

**Comment by laurelfulford** [comment]
Doing a bit of cleanup in this repo; I'm going to close this one in favour of #1122, since it has a bit more details/touches on other areas of the theme that are effected (like the article subtitle).
