### ISSUE TITLE
Add Source at the end of article using some sort of custom fields

### ISSUE THREAD

**Issue by WPArena** [Automattic/newspack-theme#505]
Several articles are sourced. Would love to see this feature.

**Comment by laurelfulford** [comment]
Hey @WPArena! We're trying to avoid adding custom fields to the theme unless it's absolutely necessary. I think this is something that could be achieved by using blocks with different styles. For example, a paragraph block + the smaller font size + a background colour would help differentiate it from the rest of the story:

![image](https://user-images.githubusercontent.com/177561/66722126-b5bad400-edbe-11e9-93c1-b51679f61f2a.png)

Or perhaps a separator block + styled text:

![image](https://user-images.githubusercontent.com/177561/66722134-d84ced00-edbe-11e9-9ced-7cbf4849d8aa.png)

I'm going to close this issue, but if have any questions about the above, please add them here!

**Comment by WPArena** [comment]
Awesome. Thanks
