### ISSUE TITLE
Newspack theme fails to install

### ISSUE THREAD

**Issue by marcustibesar** [Automattic/newspack-theme#517]
This theme fails to install from the master theme zip file. 

The error when installing states, "The package could not be installed. The theme is missing the style.css stylesheet."

**Comment by laurelfulford** [comment]
Hi @marcustibesar! 

The GitHub repo does not include the style.css file, so if you are downloading the zip from here: 

![image](https://user-images.githubusercontent.com/177561/67119315-c04ce300-f19b-11e9-9238-a179f23b0d72.png)

... it will not include the CSS. You can generate it from the theme's Sass files by running `npm install && composer install` and then `npm run build` in the theme directory. There's some more information about that under "Development Workflow" here: 

https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md#development-workflow

If you are downloading the theme from the "Releases", it should include the style.css -- you can get the latest releases here:

https://github.com/Automattic/newspack-theme/releases

I'm going to close this issue, but please let me know if this doesn't resolve the problem for you, and I can re-open to investigate further. Thanks!

**Comment by marcustibesar** [comment]
Thank you Laurel.

I am new to Github and “npm”.

So I downloaded the newspack-theme.zip file and that installs correctly. Thank you very much!

I am the lead Archivist for our family archive. The archive has been established since 2010.

We have over 975 posts and over 15,000 photos.

The archive located at https://tibesar.com is currently using the twenty-twenty theme however we believe the Newspack theme is more appropriate for our archive which grows steadily.

The theme is beautiful and very pleasing to the reader’s eye. 

We thank you for all the work and skills you’ve dedicated to Newspack.

Marcus Tibesar, Founder and Lead Archivist
The Tibesar Family Archives
https://tibesar.com

**Comment by laurelfulford** [comment]
I'm glad that worked, Marcus! 

Thanks for sharing a link to your site! That sounds like it's been a ton of work, I'm really glad to hear that the theme is working well for you. Thanks for using it!

**Comment by marcustibesar** [comment]
I have already transitioned over to Newspack. It was a breeze changing from Twenty-Twenty to Newspack. The topology and attention to detail in NewsPack is outstanding. Thank you, thank you and thank you...
