### ISSUE TITLE
Remove "Category" from category archives

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-theme#531]
**Is your feature request related to a problem? Please describe.**
The word "Category" appears on category archives which looks a bit weird for a news site. 

**Describe the solution you'd like**
We should probably remove this and have the category name styled up a bit more. There's also quite a lot of space around the category name which pushes the articles down quite a bit.

![FireShot Capture 117 - News - Brooklyn Eagle - brooklyneagle-newspack mystagingwebsite com](https://user-images.githubusercontent.com/136342/67677909-2ba56a80-f97d-11e9-97dc-07fefd865f4a.png)

**Comment by laurelfulford** [comment]
This should actually be fixable with #939 to some extent (it adds HTML around the 'Category:' etc text, which can then be used to hide it if desired).

**Comment by laurelfulford** [comment]
Closing because this can now be hidden with Custom CSS.
