### ISSUE TITLE
When the date is hidden in Content Options, the author name looks mis-aligned (issue title edited)

### ISSUE THREAD

**Issue by WPArena** [Automattic/newspack-theme#546]
Can you please add a UL List that put a beautiful colored right icon to before every element.

Secondly, when we remove the date the author name looks unaligned. So when we remove the date make the author name aligned to middle in front of author gravatar.

Thanks

**Comment by laurelfulford** [comment]
Hi @WPArena,

> Can you please add a UL List that put a beautiful colored right icon to before every element.

This kind of thing is tricky to add to the theme in a general enough way that it will work for everyone, but it looks like the 'icon list block' from the Stackable plugin might do the trick for you:

https://wordpress.org/plugins/stackable-ultimate-gutenberg-blocks/
https://wpstackable.com/icon-list-block/

I'm going to update the issue title to reflect the second issue; going forward, can you please open separate issues for each bug/enhancement/etc, just to make sure we don't lose track of anything? Thanks!
