### ISSUE TITLE
Image Block: Initial load on mobile can push caption way down

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-theme#547]
Sometimes when loading a post on a mobile device, the caption on image blocks, when floated left or right, can initially be pushed down quite a bit. You can see where the caption is in this screenshot by looking for the little block underneath the caption:

![IMG_9301](https://user-images.githubusercontent.com/177561/67908016-14aa7800-fb37-11e9-9c0a-97c3486103e9.PNG)

This often resolves after the page sits for a while. 

I'm also not sure if this is related a) the theme's image styles, b) related to AMP, or c) caused by the combination of the two. 

It also appears it can be fixed by switching the image block from `display: table` to `display: block`, and the `figcaption` from `display: table-caption` to `display: block`, at least on smaller screens. This should undergo some testing to make sure it doesn't cause other issues, though.

**Comment by claudiulodro** [comment]
This seems to be related to mobile Safari, and I believe it's a bug in their rendering engine. I've tested and can reproduce without AMP, so I think that rules AMP out. It can be consistently reproduced on mobile Safari:

1. Start with a post that has a right-aligned image. Enter Safari responsive design mode.
<img width="752" alt="Screen Shot 2019-12-16 at 10 57 22 AM" src="https://user-images.githubusercontent.com/7317227/70934701-557d2400-1ff3-11ea-85af-983c63cff631.png">

2. Switch between the different mobile device options repeatedly and/or reload the page repeatedly. Within a few tries, the caption will be forced far underneath the image when the page is re-rendered.
<img width="1432" alt="Screen Shot 2019-12-16 at 10 57 40 AM" src="https://user-images.githubusercontent.com/7317227/70934715-5e6df580-1ff3-11ea-98b3-cef81c2b9fcd.png">

3. Resizing the screen, changing any css rule, or doing anything else that would re-render the page will fix the issue.
<img width="1421" alt="Screen Shot 2019-12-16 at 10 57 53 AM" src="https://user-images.githubusercontent.com/7317227/70934724-63cb4000-1ff3-11ea-86c8-9f3adf5a92e0.png">
