### ISSUE TITLE
Image Sizes?

### ISSUE THREAD

**Issue by WPArena** [Automattic/newspack-theme#561]
Kindly guide me about the best image size that fits on all Newspack blocks like in archives and post page.

What should be the best size and media settings for large medium and thumbnail images?

**Comment by laurelfulford** [comment]
> Kindly guide me about the best image size that fits on all Newspack blocks like in archives and post page.

The best original image size for the theme is at least 1200px wide; I think if they are also about 800px tall, they should be a good size for most cases. 

On single posts and pages, the image heights aren't cropped, so if you use an image that's taller than it is wide, it will show the full image. Landscape will look best, but if there's important parts of the image near the edges, they won't be cropped out.

On archive pages, the images are cropped to landscape shapes -- a featured image on the first post will display larger (780px x 585px on desktop), and subsequent image will display landscape, but smaller (190px x 142px):

![image](https://user-images.githubusercontent.com/177561/68551594-65399500-03c3-11ea-894f-6761ce4aa844.png)

For the article block, it's pretty wide open -- it has options to display the photo as landscape, portrait, square, or without cropping at all:

![image](https://user-images.githubusercontent.com/177561/68551630-d2e5c100-03c3-11ea-8a61-2d2b9a4f4b6a.png)

It will try to use the highest quality image available for each crop size. If you're starting with a very small image, it will try to scale it up if to fill all available space -- this is to avoid issues with images being slightly different sizes when they should be the same.

Unfortunately, this can also cause display issues if you're using a lot of smaller original images; in that case, it's best to nest the block inside of a column block (so it's narrower), or pick the option to display the image to the left or right, and scale them down using the 'Image Scale' option in the right sidebar.

> What should be the best size and media settings for large medium and thumbnail images?

The theme and blocks use custom thumbnail sizes, so what you set under Settings > Media shouldn't have adverse effects. 

The content area of the theme can get up to 1200px wide, so it might make sense to increase the 'large' size to that if you plan to use it in the 'One Column Wide' template -- but that's the only thing I can think of. 

I hope this helps!
