### ISSUE TITLE
Home Page Article News Block issue?

### ISSUE THREAD

**Issue by WPArena** [Automattic/newspack-theme#562]
Currently, the home page news block is not fetching articles from sub categories. It's just fetching articles from the selected category. I want that it fetch articles from parent and subcategories.

Can you please fix it?

**Comment by laurelfulford** [comment]
Thanks for the report, @WPArena!

I've moved this issue to the Newspack Blocks repo, since that's where the code changes will need to happen: 

https://github.com/Automattic/newspack-blocks/issues/207

I'm going to close this one and any activity will happen on the issue above.
