### ISSUE TITLE
CPT is broken

### ISSUE THREAD

**Issue by techengage** [Automattic/newspack-theme#591]
The CPT on NewsPack theme is broken. The layout is broken. It should adopt a simple post/page layout.

**Comment by laurelfulford** [comment]
Thanks for reporting this issue @techengage!

This is what I get when I view a CPT:

No featured image:

![image](https://user-images.githubusercontent.com/177561/69653310-d87c1180-1027-11ea-940c-dec62a64aa54.png)

With featured image:

![image](https://user-images.githubusercontent.com/177561/69653519-3577c780-1028-11ea-9a56-c0f9cb52c5b6.png)

Sidebar: 

![image](https://user-images.githubusercontent.com/177561/69653420-02cdcf00-1028-11ea-9455-57a3d174592e.png)

* The content is too wide, filling the whole space
* The sidebar wraps and appears below the comments
* The vertical spacing around the title/post meta is a bit weird; it should also have a border underneath it when there's no featured image

We can look into fixing these; if you're seeing any other issues that are missing here, just let us know!

**Comment by techengage** [comment]
That's a perfect explanation. Yes, it's the errors, I can find at the moment.
