### ISSUE TITLE
Hide Author option for seldom categories and on per post basis

### ISSUE THREAD

**Issue by techengage** [Automattic/newspack-theme#599]
It's great if we have both the option of hiding the author on edit post screen and edit category page. 

It will be great for news sites where only editors report.

**Comment by laurelfulford** [comment]
Thanks for filing this, @techengage!

Given that this is an older request that hasn't come up again, I'm going to close this issue for now, but it can be reopened or a new issue can be created if more people are interested in this functionality in the future. 

In the short-term, Custom CSS may help with this request -- I'm not sure if you are trying to do something like this site-wide, or on a per category basis, but both should be possible. The following should work for a specific category, it will just need to be updated to use the correct slug from your site:

```
/* Archives */
.archive .category-[slug] .byline,
/* Search */
.search .category-[slug] .byline,
/* Single posts */
.cat-[slug] .entry-header .author-avatar,
.cat-[slug] .entry-header .byline,
/* Homepage Posts block */
.wpnbha .category-[slug] .entry-meta > a,
.wpnbha .category-[slug] .entry-meta .byline {
    display: none;
}
```

... or to hide author site-wide, something like this should work:

```
/* Archives */
.archive .byline,
/* Search */
.search .byline,
/* Single posts */
.entry-header .author-avatar,
.entry-header .byline,
/* Homepage Posts block */
.wpnbha .entry-meta > a,
.wpnbha .entry-meta .byline {
    display: none;
}
```

I'm going to close this issue for now but please let us know if you have any questions about the above!
