### ISSUE TITLE
Default Setting of Featured Image for Migration

### ISSUE THREAD

**Issue by akkiverma** [Automattic/newspack-theme#601]
Hello,

First of all many thanks for creating this great theme. I want to migrate to using Newspack at earliest but there is one issue I am facing which is theme dependent. 

I want to keep default setting of featured image to 'Behind Title' for all posts, but I am afraid when I'll change the theme, it'll keep the default setting of the large featured image for all posts and I'll have to open each post and change it to behind title. Is there any way via using any code or something by which I could change the default to behind title or the Small featured image.

**Comment by akkiverma** [comment]
Awaiting if anyone can advice me how to do it. I am all ready to migrate, only this step is remaining.

**Comment by laurelfulford** [comment]
Unfortunately, there's no good way to do this now, @akkiverma, but it would be handy to be able to change the default site-wide.

I'm going to switch this issue to an enhancement request, so we can dig into this further!

**Comment by akkiverma** [comment]
Yes please, not just me, but many of my friends too who want to migrate to newspack but this is the only hurdle which we've not been able to solve in any way.  I migrated to full AMP using Newspack on https://www.reviewcenter.in/ and now I don't want to revert to old theme. Mobile layout looks great but on desktop, the featured image is taking whole screen space. I wish if this option can be taken with priority. Thanks

**Comment by laurelfulford** [comment]
Closing in favour of #609.
