### ISSUE TITLE
Featured Image Size too Large for Desktop

### ISSUE THREAD

**Issue by akkiverma** [Automattic/newspack-theme#602]
As per Google recommendation, in the post layout, there should be a featured image at top for any post. I am force keeping using AMP for mobile and desktop both. And the by default featured image settings shows a very big size of the image on the desktop. Even the option of the small featured image covers half of the page. Also, the behind and beside option covers the whole page on the desktop. 

This is not how a normal blogpost or News layout should be in my opinion. The first view only offers the title and image and if I'll add an AD later on, there will be no space for content. 

Usually what news sites do is they offer a small version of the image on desktop too, like these -  

https://www.ndtv.com/offbeat/boy-writes-to-kerala-police-about-delay-in-cycle-repair-their-response-wins-hearts-2140682?pfrom=home-lateststories

https://timesofindia.indiatimes.com/india/india-announces-450-million-line-of-credit-to-sri-lanka/articleshow/72292830.cms

https://timesofindia.indiatimes.com/business/india-business/india-braces-for-shock-gdp-as-centre-scrambles-to-spur-economy/articleshow/72288992.cms

https://www.indiatoday.in/india/story/pm-announces-450-million-line-of-credit-to-sri-lanka-after-talks-with-gotabaya-rajapaksa-1623684-2019-11-29 (loved this layout most)

https://edition.cnn.com/2019/11/29/africa/russian-mercenaries-mozambique-intl/index.html

Here's what I've done so far to minimize the issue, but I think it'll be great if the theme main serves a small featured image by default in all layouts:

https://newspack.ankitchugh.com/test-title-test-post-test-title/

https://newspack.ankitchugh.com/styling/

**Comment by laurelfulford** [comment]
Hi @akkiverma,

There's an option under Featured Images, when editing a post, where you can switch the image to use a smaller version in the content area:

![image](https://user-images.githubusercontent.com/177561/70070750-f8bc4b00-15a8-11ea-8297-d29a8a384bd4.png)

#604 could also help here when completed -- it's a feature request to add an option to hide the featured image on an individual post, so you can add it to show with the homepage blocks, but hide it on the post itself and insert a smaller image of your choice into the content.

I think the two options above should help, so I'm going to close this issue, but please comment here if you have any further questions -- thanks!

**Comment by akkiverma** [comment]
Yes, I saw this, awaiting eagerly for the update to come with this feature.
