### ISSUE TITLE
An option to make Featured Posts "Hidden" or "Any Other" for all posts Site Wide

### ISSUE THREAD

**Issue by akkiverma** [Automattic/newspack-theme#609]
I see that the option to hide Featured Image has been approved and will be included in the future updates. But there is also a need to have this feature to be enabled site-wide too so that the publishers don't have to open each existing post and set the required option. or this way it'll be way better if the site-wide feature image options may contain all of the existing options like:

- Default
- Small
- Behind
- Beside
- Hidden

Please consider providing this option. It'll be a very big help.

**Comment by laurelfulford** [comment]
Hi @akkiverma -- as I understand it, this sounds really similar to #601 (setting a default would work for all new and existing posts, unless they have one of the other options selected). Please let me know if I'm missing something, or I can close #601 in favour of this issue. Thanks!

**Comment by akkiverma** [comment]
Yes please, as this is a better idea, please close #601 and take this as preferred.

**Comment by laurelfulford** [comment]
Great - thanks for confirming, @akkiverma!
