### ISSUE TITLE
Sticky Header on both Mobile & Desktop

### ISSUE THREAD

**Issue by akkiverma** [Automattic/newspack-theme#621]
**Is your feature request related to a problem? Please describe.**
Sometimes the blog posts are quite long and since AMP doesn't have JUMP to TOP button, it can be sometimes very frustrating scrolling back to the top.

**Describe the solution you'd like**
I've checked code and the amount of CSS required for adding just JUMP to TOP button, hence rather I think it is better to provide an option for enabling sticky header on both desktop and mobile so that it becomes easier for users to navigate to other pages. 

**Describe alternatives you've considered**
There is none so far.

**Additional context**
I am hoping if sticky header can also have a search button along with the menu button when on mobile.

**Comment by laurelfulford** [comment]
Thanks for filing this issue, @akkiverma! 

#84 sounds like a similar enhancement request; I'm going to close this in favour of that older issue, but copy over the additional details you've provided.
