### ISSUE TITLE
صالون دونير

### ISSUE THREAD

**Issue by mageed11** [Automattic/newspack-theme#622]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**

**Screenshots**

**Expected behavior**

**Comment by laurelfulford** [comment]
Hi @mageed11! It looks like this was opened in error, so I'm going to close it.

 If that's not the case, please open a new issue, and follow the template to describe the issue you're seeing, and we can take a closer look. Thanks!
