### ISSUE TITLE
Urgent Broken Links on Home Page

### ISSUE THREAD

**Issue by TechAbout** [Automattic/newspack-theme#623]
Author URLS on home page is broken under articles. Please fix it urgently.

**Comment by laurelfulford** [comment]
Hi @TechAbout - thanks for filing this issue!

I'm not having any luck recreating this, but I might not have the same settings as you do.

Are you experiencing the issue with the theme (like the blog posts page), or the Homepage Article block from the Newspack Blocks plugin? (https://github.com/automattic/newspack-blocks).

What version of the theme and blocks plugin are you using? Is it the master branch, or one of the releases you've downloaded?

Any additional details will be a huge help -- thanks!

**Comment by TechAbout** [comment]
I am using the latest version. The issue can be find here https://techengage.com

Please check on the homepage. Author URLS are broken.

Thanks

**Comment by laurelfulford** [comment]
Thanks @TechAbout -- I have it now! 

Looking into a fix.

**Comment by laurelfulford** [comment]
This should now be fixed in the master branch of the Newspack Blocks plugin (https://github.com/Automattic/newspack-blocks), and will be available in the next release!
