### ISSUE TITLE
Support for Yoast Breadcrumbs

### ISSUE THREAD

**Issue by akkiverma** [Automattic/newspack-theme#626]
Hi,

Since at present the theme has no inbuilt breadcrumbs feature, maybe if adding native support of Yoast breadcrumb would come handy for many. I implemented those by adding Yoast breadcrumb code in `entry-header.php` file just below `<?php if ( is_singular() ) : ?>`

Yoast Breadcrumb Code: 

```
<?php
if ( function_exists('yoast_breadcrumb') ) {
  yoast_breadcrumb( '<p id="breadcrumbs">','</p>' );
}
?>
```

CSS I am using for it:

```
p#breadcrumbs {font-size: 12px; margin: 5px 0 8px 0; font-variant-caps: petite-caps; }
#breadcrumbs > span > span > a, .featured-image-behind #breadcrumbs > span > span > span > a { color: white; }
```

Just sharing as this might be useful for many and if can be supported natively by providing an option like Enable Yoast Breadcrumb, it would be great. To see this implementation live - https://www.reviewcenter.in/

**Comment by thomasguillot** [comment]
Hi @akkiverma, thank you for your suggestion. Yoast Breadcrumbs support has been added to theme (#855)
