### ISSUE TITLE
Predefined Height & Width of Featured Image Size

### ISSUE THREAD

**Issue by akkiverma** [Automattic/newspack-theme#629]
Hi,

In the theme version 1.0.0-alpha.22, the featured image size was predefined as width = 1200 irrespective of whatever the image maybe.

I would like to keep that same as previous as it resolved a big issue of AMP image size. Can you please tell me how to keep the featured image size predefined for Hidden and Small layout. This is how most news site I've seen do, they upload a smaller size of the image but in the code, it is defined as 1200 x 650.

Like here `<figure class="post-thumbnail"><amp-img width="1023" height="575"`

It was always 1200 and now it is showing actual width. I would rather want to show it as width = 1200 and height = 650.

Although it should be natively supported in my opinion, if you don't want to keep it that way, can you please tell me a way for now to do it. When I was on the last version, see this, how after migrating to newspack theme, this issue was auto-resolving. And now I am sure it'll start increasing back.

![2423242](https://user-images.githubusercontent.com/20245997/70533861-f1380b80-1b7f-11ea-86d5-c01a681eefdf.png)

**Comment by akkiverma** [comment]
I just checked, when I enabled hidden featured image setting, it didn't add any image size nor <figure class="post-thumbnail"></figure> was defined.

**Comment by laurelfulford** [comment]
@akkiverma Apologies for following up on this issue so late! 

It does look like 1.0.0-alpha.23 included some pretty significant changes to the featured images on posts, including adding the ability to pick a featured image placement default, and having the 'Large' image option (which is 1200px) fall back to a smaller image size if the original is too small (under 1200px wide). If I remember correctly was to avoid displaying smaller images in a sub-optimal way. 

The functions used for this are written in a way that they can be overwritten by a child theme, if the original behaviour is still desired. They are:

[`newspack_featured_image_position()`](https://github.com/Automattic/newspack-theme/blob/master/newspack-theme/inc/template-functions.php#L8) -- this function gets the current featured image position setting (from the Customizer or current post), and also includes a check to make sure the [original image size is large enough](https://github.com/Automattic/newspack-theme/blob/master/newspack-theme/inc/template-functions.php#L44-L46) -- that could be overridden in a child theme to remove the size check and always return 'large'.

[`newspack_post_thumbnail()`](https://github.com/Automattic/newspack-theme/blob/969e4837218d419cd50aac4e18a367d4a7d46000/newspack-theme/inc/template-tags.php#L332) could be used to change the image output, if you wanted to hard-code a height and width value. 

Again, apologies for the late reply to this issue! I'm going to close it, but please let us know if there are any questions!
