### ISSUE TITLE
Auto Featured Image

### ISSUE THREAD

**Issue by akkiverma** [Automattic/newspack-theme#637]
Not sure if this should be a theme feature or the plugin feature to request, but is it possible if newspack may automatically set the attached image as the featured image (or the first image in post content) when posting via email. This is useful when we try to post content via email using jetpack and Jetpack doesn't support adding featured image via email at all. 

Also further options can be like setting default category - News Category.

**Comment by laurelfulford** [comment]
Thanks for the suggestion, @akkiverma!

I think this would be a theme-level thing, though it wouldn't just be when the post is shared via email -- it would be an option to always use the first image in post as a fallback featured image.

I know this is currently possible using Jetpack's Content Options, but I'm not sure how that'll mesh with all the other featured image settings in the theme. So it'll will need some investigation to figure out whether it would be possible. 

I think if we did do this, we would probably want the single post view to 'hide' the featured image, or not show the first image as a featured image, but just use it as a fallback elsewhere (email, homepage blocks, archives, etc).

**Comment by akkiverma** [comment]
That's understandable. You've to look at a broad spectrum than what I see from my side :)

**Comment by laurelfulford** [comment]
Given that the featured image settings have gotten a lot more complicated since this request, and we haven't had additional requests for this feature, I'm going to close this issue. If there's renewed interest at any point, we can definitely reopen it or create a new issue!
