### ISSUE TITLE
Disable comments on Pages

### ISSUE THREAD

**Issue by claudiulodro** [Automattic/newspack-theme#638]
**Is your feature request related to a problem? Please describe.**

Should the comments form be displayed on Pages? These are usually About, Donate, Contact, etc. and probably shouldn't have the comment form. While setting up sites, I often have to disable the comment form on Pages I encounter, because it doesn't make sense to let people comment on them.

**Describe the solution you'd like**

Suppressing the comment form for Pages on the frontend is straightforward, but the "Discussion > Allow comments" setting would still show up in the editor for a Page. I haven't seen a good solution for that part in my initial search, otherwise I'd have just opened a PR. :)

**Describe alternatives you've considered**

🤷‍♂ We could just have comments on Pages, I suppose, and people would need to turn them off at the individual Page level if they don't want them.

**Additional context**

<img width="891" alt="Screen Shot 2019-12-18 at 11 59 00 AM" src="https://user-images.githubusercontent.com/7317227/71118889-cf491500-218d-11ea-9eb6-2c02e45623c4.png">

**Comment by laurelfulford** [comment]
> We could just have comments on Pages, I suppose, and people would need to turn them off at the individual Page level if they don't want them.

Good catch!

For some reason I thought you could turn off comments for all pages under Settings > Discussion, and leave them in tact for posts, but it doesn't look like that's true. There are [plugins that do that](https://en-ca.wordpress.org/plugins/disable-comments/), but I think it would make sense to remove the comment code from the page template in the theme. It's easier, removes a step to setup, and we can always circle back to the plugin option if someone does want comments on a page down the road.

**Comment by laurelfulford** [comment]
When testing this, I noticed on a couple test sites that any page I created had comments disabled. After digging around a bit, I found this has been a WordPress default setting for a few years:

https://make.wordpress.org/core/2015/07/06/comments-are-now-turned-off-on-pages-by-default/

@claudiulodro is there a specific site you've noticed that comments are enabled when you create pages without changing that setting? We can still remove the code from pages in the theme if need be, but this might signify that something else is going on (and it'd be nice to let folks turn on page comments in certain cases, if it's something they need).

**Comment by claudiulodro** [comment]
Good catch. That makes sense. It's just something I've encountered while working on existing, converted sites, but now I believe comments on those pages are user error (or possibly pages created before 2015) so I don't think we need to worry about it. Thanks for digging that change announcement up!
