### ISSUE TITLE
Videos not filling available space

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-theme#652]
I specifically noticed this with the Vimeo block, but it should also be tested with YouTube, VideoPress, and general videos.

When you add a video to the full-width template, it doesn't fill up the available space -- it appears to stop around 800px. 

The video should scale up to fill the space, to avoid weird spacing.

**Comment by adekbadek** [comment]
@laurelfulford I could not reproduce. I've added a Vimeo block, but with any template (`Default`, `One column`, `One column wide`) it scales ok to fill paragraph width.

**Comment by laurelfulford** [comment]
Thanks for testing, @adekbadek! 

I retested, and got it to work correctly when I shut off AMP -- so it looks it's only happening when AMP is enabled. I totally missed that when I first saw this!

With AMP disabled:

![image](https://user-images.githubusercontent.com/177561/71942762-20d43680-3173-11ea-9ca5-bd73632f840c.png)

With AMP enabled:

![image](https://user-images.githubusercontent.com/177561/71942772-2af63500-3173-11ea-9386-25a10dd07de1.png)



Just let me know if enabling AMP still doesn't change it for you -- there might be another factor at play here :)

**Comment by adekbadek** [comment]
Still can't reproduce, with or without AMP enabled :( 
I've set up a minimal [example on jurassic.ninja](https://guilty-stink.jurassic.ninja/2020/01/08/hello-world/)

**Comment by laurelfulford** [comment]
Thanks @adekbadek! I am totally stumped 😕 

I can see the video scaling correctly on your example site (thanks for putting that together!). But when I try the same thing -- on another jurassic.ninja site, hoping to rule out some weirdness on my localhost -- I [can't make it work](https://continuing-eyed.jurassic.ninja/2020/01/08/vimeo-test/).

I tried using each of the different settings provided by AMP for the block, as well as both of our videos (on the off-chance it had something to do with the source??), but no dice. My JN site is running the latest plugin/block/theme release. I originally spotted this on [one of our staging sites (about 2/3 down the homepage)](https://hawaiibusiness-newspack.newspackstaging.com/), and it also should be running the latest. 

I can try digging into this a bit more today and hopefully it's just some silly thing I'm missing!

**Comment by laurelfulford** [comment]
Comparing our test sites, it looks like the issue is the URL used:

If you use the format `https://vimeo.com/#####`, the video scales correctly. 

If you use `https://player.vimeo.com/video/#####`, the video displays too small with AMP enabled.

Strangely, on publish both URLs are switched to the `https://player.vimeo.com/video/#####` format. 

Closing this as a theme issue, but it seems like the URLs should be treated the same; will do some digging and figure out whether this needs to be reported as a Gutenberg thing, or an AMP thing. 

(Thanks for the help sleuthing, @adekbadek! 🔍)
