### ISSUE TITLE
Social Menu: Add more icon options

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-theme#722]
Three that could immediately be helpful include:
* ~~Phone (for phone number)~~
* Pushbullet
* Telegram

**Comment by laurelfulford** [comment]
From #1269 - make sure to include the t.me URL format when adding Telegram!

The Phone icon was added in https://github.com/Automattic/newspack-theme/pull/849.

**Comment by yogeshbeniwal** [comment]
> From #1269 - make sure to include the t.me URL format when adding Telegram!

Does that mean Telegram is supported by default, without any code changes?

**Comment by laurelfulford** [comment]
Closing with #1511.
