### ISSUE TITLE
Incorrect Avatar Crops On Rivard Report

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-theme#752]
**Describe the bug**
On Rivard Report, some author avatars are incorrectly cropped. At first glance, it appears this occurs for any avatars that are not perfect squares.

- I initially suspected this was a thumbnail regeneration issue, so I ran `wp media regenerate` on the avatar. No change. Also downloaded the original and re-uploaded. No change.
- The problem is not limited to multi-author stories. Here's a single-author story with the same: https://therivardreport.com/what-it-will-take-to-convince-san-antonio-voters/
- Tried using the same Avatar on a local instance and here it worked fine. On local, Jetpack Image Accelerator is not activated, which may be a clue.

**Screenshots**
Live example: https://therivardreport.com/reports-detail-energy-waste-in-northside-isd-citys-largest-school-district/

<img width="1685" alt="Screen Shot 2020-02-02 at 3 48 21 PM" src="https://user-images.githubusercontent.com/1477002/73615152-76b1c800-45d3-11ea-92f0-99ba7b99a142.png">

**Expected behavior**
All avatars are perfect un-cropped circles.

**Comment by jeffersonrabb** [comment]
This appears to affect any avatar that is not a perfect square.

**Comment by laurelfulford** [comment]
I've narrowed it down to the WP User Avatar images + Jetpack site accelerator -- both together either squish the images to fit (no AMP), or show the uncropped edges, like in your screenshots (AMP enabled).
