### ISSUE TITLE
Slide-out menu

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-theme#766]
A couple of publishers have asked to have a "hamburger" menu on all device widths that slides out from the side of the page when clicked.

One example comes from the St. Louis Post-Dispatch:

![Screenshot from 2020-02-11 11-57-29](https://user-images.githubusercontent.com/136342/74235347-b14bec80-4cc6-11ea-81c2-b2ab5fae29aa.png)

If we implement something like this we should take care to help publishers use it effectively, and avoid it being a "dumping ground" for anything that won't fit in the primary menu.

**Comment by laurelfulford** [comment]
This is completed, so closing this issue.
