### ISSUE TITLE
Feature: Featured Image in RSS feeds

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-theme#795]
RSS feeds don't currently use the featured image for an article, only those that are added into the content itself. While there isn't a mechanism in the [RSS spec](https://validator.w3.org/feed/docs/rss2.html) for adding an image for each item, it might make sense to simply add the featured image to the top of the content, which would largely match how it's presented on the site itself.

**Comment by SanjayKumarMonu** [comment]
Hi @laurelfulford @philipjohn 

Wordpress by default isn't sporting **Featured Image in RSS feed**. However, you can enable the same feature in your theme by pasting the code (which I have mentioned below) in your themes function.php file last lines.

`// display featured post thumbnails in WordPress feeds
function wcs_post_thumbnails_in_feeds( $content ) {
    global $post;
    if( has_post_thumbnail( $post->ID ) ) {
        $content = '<p>' . get_the_post_thumbnail( $post->ID ) . '</p>' . $content;
    }
    return $content;
}
add_filter( 'the_excerpt_rss', 'wcs_post_thumbnails_in_feeds' );
add_filter( 'the_content_feed', 'wcs_post_thumbnails_in_feeds' );
`

Hope, that solves the issue. Thank me later 😊

Regards,
Sanjay
