### ISSUE TITLE
Typography: Can't add fonts from Hoefler & Co's cloud typography

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-theme#798]
Hoefler & Co's cloud-based fonts are supported by the theme, but their unusual way of declaring fonts isn't being accepted. 

Each font needs to have two faces declared: an "A" file and a "B" file (example "Mercury SSm A", "Mercury SSm B"). However, the Header and Body fields don't want you to add the double-quotes -- it's automatically added by the theme. This means either the two fonts are combined in one set of quotes, or if you add quotes yourself, they're escaped.

The code should either: 
* Check for single or double quotes surrounding the font that's added, and if they are there, don't add more, or
* Check for a comma and use that as a guide for where to add more quotes. 

Hoefler & Co's user guide: https://www.typography.com/user-guide/included

**Comment by adekbadek** [comment]
@laurelfulford  – is this still relevant? If so, please provide exact reproduction steps.

**Comment by laurelfulford** [comment]
@adekbadek It's still something that's not functioning correctly in the theme, but so far we don't actually have any publishers using Hoefler & Co fonts -- so it's not something directly affecting any sites yet, and has been a lower priority. 

A paid account to Hoefler & Co is required to fully reproduce the font not loading, but you can use partial steps to reproduce:

1. Going off of the example from Hoefler & Co (https://www.typography.com/user-guide/included - click the Using Projects tab), copy the font face string `"Whitney SSm A", "Whitney SSm B"` -- these match the format you'd get from Hoefler & Co to go with their provided CSS.

![image](https://user-images.githubusercontent.com/177561/151636385-bfdcf947-7de0-4491-a926-7689a44cc602.png)

2. Navigate to Customizer > Typography, and paste the font faces as provided in the Heading or Body field. 
3. Publish. 
4. Use the Inspector to check one of the elements your font should be applied to (like if you've added it in the Heading field, inspect one of the headings) -- both font names will be wrapped in an additional set of double-quotes (so browsers will try to interpret them as one name), and the quotes for each of the individual faces will be escaped, like this:

`font-family: "\"Whitney SSm A\", \"Whitney SSm B\"","Georgia","serif";`

![image](https://user-images.githubusercontent.com/177561/151636621-8ea8bfac-7f35-43ee-801c-12c9cfd1debd.png)

Honestly at this point, it would be equally valid to retire this as a font option, since it doesn't work and over two years in, hasn't been used. Let me know what you think!

**Comment by laurelfulford** [comment]
Given Hoefler & Co's [data collection when using the Cloud.typography service](https://www.typography.com/policies/privacy), specifically this bit:

> Computer Information Collected. Additionally, H&Co automatically collects certain non-personal computer or device-related information from visitors to the Website (and, **if you are a subscriber to the Cloud.typography service, visitors to your website**), including the operating system (e.g. Mac OS, iOS, Windows, Android), the visitor’s IP address, and the web browser (e.g. Safari, Firefox, Chrome) and for visitors to the websites of Cloud.typography subscribers, the webfonts served and the referring URL (collectively “Computer Information”).

... I think we should deprecate this support and recommend fonts from Hoefler & Co be purchased and uploaded to the site instead.
