### ISSUE TITLE
Post Format support

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-theme#802]
A publisher has mentioned wanting a feature that is very similar - if not identical - to post formats. While post formats haven't been in the default WP themes since 2017, the plumbing is still there and could still be used.

Essentially, the use case is that the home page, and other archives, could have a simple blog-style stream but are showing what's happening now, with a mix of update styles.

Some updates may be full articles, and would be treated as they are now, but some might be a quick status update (perhaps a traffic report) or an image (the weather forecast maybe). Each of these non-standard posts would get a different visual treatment, and often wouldn't need to link anywhere.

**Comment by laurelfulford** [comment]
I haven't done anything with Post Formats in forever, but this does sounds very similar to that functionality. It sounds like this so far would cover Standard Aside/Status, and Image -- do you know if there are other content types they were thinking of?

**Comment by laurelfulford** [comment]
We did end up adding support for the Aside format to both the theme and blocks; I'm going to close this request for now until we have further requests for specific post formats.
