### ISSUE TITLE
Feature Request: Collapsable Comments

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-theme#804]
The comments area can be pretty chunky. Some publishers want the ability to compact this down so it's not such a huge part of the page.

One option might be to allow the comments area to be collapsable, so that it's still obvious that a comment area exists, and that visitors can comment, but it's not completely visible by default.

**Comment by laurelfulford** [comment]
I think adding an option to collapse the comments would be a good one -- and very easy to make AMP-compatible. :)
