### ISSUE TITLE
Please Bring an Option to Show Modified Date on Post Pages

### ISSUE THREAD

**Issue by SanjayKumarMonu** [Automattic/newspack-theme#823]
Hi Newspack Theme Developers,

Sanjay Here. First of all I would like to congratulate and show you guys my gratitude for building such an awesome theme. 😊

Today, I come to suggest you a feature called **Modified Date**. Right now, Newspack Theme doesn't have an option to show Modified Date on Post Pages as you can see there are some posts that need to be updated regularly.

Also, the Theme needs this feature because, Search Engines prefers updated content and infact search engines also displays the post date in the snippet if a site administrator give the search engine the preference to do so.

That's why I thought it would be a great feature to include in Newspack. Let's see Whether you guys find it interesting as well as useful or not.

Regards,
_Sanjay_

**Comment by laurelfulford** [comment]
Belatedly realized this is a duplicate issue, so I'm closing in favour of #598.
