### ISSUE TITLE
Add option to make header sticky

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-theme#826]
An option under Header Settings to set the header to sticky could be very helpful, and is common on news sites.

The behaviour on a site like https://www.journaldugeek.com/articles/ is also really cool -- the header re-appears when you start scrolling back up, rather than being always fixed.

The main potential issue is height: the header's height, in part, depends on the size of the logo, so it can be variable. We will need to 'know' the height to set a proper sticky menu. This is usually done with JavaScript, but using AMP limits what's available there. So this will need digging into -- it may be possible to use the same scroll-position logic that's used in the popups, or we could set a fixed height for the headers with this setting -- overriding the custom logo size -- to ensure they're a consistent height.

**Comment by thomasguillot** [comment]
> we could set a fixed height for the headers with this setting -- overriding the custom logo size -- to ensure they're a consistent height.

I would do this because:

1. We don't have to worry about JS. It can be done with CSS-only.
2. We avoid bad practice if a site has a massive fixed header that takes 50% of the screen height.

**Comment by laurelfulford** [comment]
I'd hoped to use AMP's [float-in-top](https://amp.dev/documentation/components/amp-fx-collection/#float-in-top,-float-in-bottom) effect for this (which has the header scroll away with the page, but appear again when you scroll back up), but it requires you to have `overflow: hidden` on the element, which means, for the header, that the menu dropdowns get cut off.

**Comment by laurelfulford** [comment]
This is a duplicate of a much older issue; closing in favour of #84.
