### ISSUE TITLE
Header broken with AMP on smaller screens

### ISSUE THREAD

**Issue by adekbadek** [Automattic/newspack-theme#838]
**Describe the bug**
With AMP enabled, the site logo image is too wide, and causes a layout issue:

![image](https://user-images.githubusercontent.com/7383192/77099373-1c9a8400-6a14-11ea-98be-fb6e92f1977a.png)

With AMP plugin deactivated, it's ok:

![image](https://user-images.githubusercontent.com/7383192/77099411-2fad5400-6a14-11ea-80b5-f08272325e22.png)

**Expected behavior**
The header, when AMP plugin is active, should look as it does with the plugin deactivated.

**Comment by laurelfulford** [comment]
Noting that we have some weird image sizing issues with the logo in the footer, too, when AMP is enabled. I suspect it's the same problem.

**Comment by laurelfulford** [comment]
The underlying issue seems to have to do with how AMP sizes images, and the logo having a `max-width` that's potentially wider than the image's actual width on mobile screens (it's 175px on tablet-sized screens and smaller). 

The `amp-img` element always takes up the full max-width.
