### ISSUE TITLE
newspack-theme-master will not install due to missing file

### ISSUE THREAD

**Issue by daniel-quire** [Automattic/newspack-theme#841]
**Describe the bug**
When uploading the Theme "Newspack - Theme Master" zip file to a fresh Wordpress installation, I get the following error: 

"Installing Theme from uploaded file: newspack-theme-master.zip
Unpacking the package…

Installing the theme…

The package could not be installed. The theme is missing the style.css stylesheet.

Theme installation failed."

**To Reproduce**
1. Go to Appearance > Themes > Add New
2. Click on 'Upload Theme'
3. Navigate to newspack-theme-master.zip on your local harddrive and select to upload

**Expected behavior**
I expected that the Newspack theme would install without error and be functional. Note: I installed this same theme recently and it worked fine on another site.

**Comment by laurelfulford** [comment]
Hi @daniel-quire! 

Based on the zip name, it sounds like you downloaded the .zip of this GitHub repo, which is kind of like the development version of the themes, and can't be installed as is on WordPress sites. 

If you go to the Releases tab (https://github.com/Automattic/newspack-theme/releases) you will be able to download versions of the theme that can be installed as is on sites. 

I'm going to close this issues, but if you run into any issues with the themes downloaded from the Releases tab, please let us know!
