### ISSUE TITLE
Infinite Scroll for both non-AMP & AMP Posts

### ISSUE THREAD

**Issue by akkiverma** [Automattic/newspack-theme#863]
Hello,

Will you be considering adding an infinite scroll feature in the theme in the coming days? Also want to know if related posts feature is available to use in the latest version?

**Comment by laurelfulford** [comment]
Hi @akkiverma!

We don't have plans to add infinite scroll to the theme in the immediate future. Technically at the moment the theme does include support for Jetpack's infinite scroll, but it doesn't work on the static front page, or with AMP -- it works on WordPress archive pages, like the blog posts page or category/tag/etc archives. 

The closest option right now is that the Homepage Posts blocks do have the option to include a 'Load More' button, which will load more posts using the same query as the block currently uses (so if it's restricted to a specific category, for example, it will only load posts from that same category). Unfortunately, pairing infinite scroll with block-based layouts like Newspack uses is really tricky. 

> Also want to know if related posts feature is available to use in the latest version?

The theme doesn't have its own related posts baked in, but we've been using Jetpack's related posts with it (https://jetpack.com/support/related-posts/) and it's been working well; is that what you mean?

**Comment by akkiverma** [comment]
I have moved to full AMP. It is okay to use jetpack infinite scroll feature but since it doesn't support AMP, can't use that as well :(
I required it to use only on blog posts only, not on the homepage. 

Also regarding the jetpack related posts, I am not really a big fan of that as when I tried it, it kept showing irrelevant articles as related. If you can add support for any other plugin like say YARPP or any other, which may be AMP compatible too, that'll be great.

**Comment by laurelfulford** [comment]
Apologies for following up on this so late! 

It looks like YARPP doesn't need any integration -- it can be installed and set to show automatically on posts, or inserted via shortcode if you want more control, and it works with AMP enabled. 

I'm going to close this issue, but please comment if you have any questions!

**Comment by yogeshbeniwal** [comment]
> We don't have plans to add infinite scroll to the theme in the immediate future.

@laurelfulford May i know if making infinite scroll on single post is on roadmap in immediate future?
