### ISSUE TITLE
Header: Option to have simplified header on subpages

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-theme#877]
For the header, add an option to have a simplified header on subpages, similar to how NYT hands features:

[**Homepage**](https://www.nytimes.com): 
![image](https://user-images.githubusercontent.com/177561/79006475-19278380-7b0e-11ea-9aca-fece1f26c49e.png)

[**Subpage A**](https://www.nytimes.com/2020/04/10/us/coronavirus-updates-usa.html?action=click&module=Spotlight&pgtype=Homepage): 
![image](https://user-images.githubusercontent.com/177561/79006503-293f6300-7b0e-11ea-9922-f0d4a72d4423.png)

(The Coronavirus banner is not standard). 

[**Subpage B**](https://www.nytimes.com/2020/04/09/us/politics/amish-coronavirus-ohio.html?action=click&module=News&pgtype=Homepage)
![image](https://user-images.githubusercontent.com/177561/79006663-7d4a4780-7b0e-11ea-9931-7bf634a2e845.png)

[**Subpage C**](https://www.nytimes.com/2020/04/09/t-magazine/viola-lanari.html)
![image](https://user-images.githubusercontent.com/177561/79007249-9e5f6800-7b0f-11ea-9452-d880c1676e01.png)

**Comment by mtfreepress** [comment]
We'd like to have something like this. 

Here's what our current header looks like: 

<img width="710" alt="Screen Shot 2020-05-01 at 1 23 59 PM" src="https://user-images.githubusercontent.com/64612380/80835055-37cde700-8baf-11ea-86d7-da366f5fec03.png">

And it'd be great if it could be simplified on a feature article page to look something like this: 

<img width="730" alt="Screen Shot 2020-05-01 at 1 25 08 PM" src="https://user-images.githubusercontent.com/64612380/80835119-57650f80-8baf-11ea-8d3b-aeb9a046b9b4.png">
