### ISSUE TITLE
Newspack sites appear significantly distorted when JavaScript is disabled (AMP-related?)

### ISSUE THREAD

**Issue by avcascade** [Automattic/newspack-theme#922]
**Issue**: If JavaScript is turned off/disabled in a user's browser, sites running the Newspack theme will appear distorted, with large amounts of whitespace separating elements near the top of the page. Other elements will load on top of adjacent elements. @laurelfulford thinks amp-sidebar is kind of blowing up when JavaScript is off. 

**Examples:**
- [The Lens](https://thelensnola.org/)
- [Technode](https://technode.com/)
- [El Soberano](https://elsoberano.org/)

**To reproduce the behavior:**
- Disable JavaScript in your browser (tools like [NoScript for Firefox](https://addons.mozilla.org/en-US/firefox/addon/noscript/) make this very easy)
- Load a Newspack site (pick one of the examples above)
- Observe the distortion 

**Screenshots:**
See attached. 

**Desired/expected behavior:**
Sites running the Newspack theme should [gracefully degrade](https://www.nngroup.com/articles/graceful-degradation-of-scalable-internet-services/) if JavaScript is turned off or not available. If not all functionality is available due to no JavaScript, that's fine, but the site should at least render properly, without massive distortion.

**Comment by avcascade** [comment]
Screenshots! 
[NOLA lens -- No JavaScript -- In-depth news and investigations for New Orleans - The Lens - thelensnola.org.pdf](https://github.com/Automattic/newspack-theme/files/4596107/NOLA.lens.--.No.JavaScript.--.In-depth.news.and.investigations.for.New.Orleans.-.The.Lens.-.thelensnola.org.pdf)
[El Soberano - No JavaScript - La plataforma de las organizaciones y movimientos socia_ - elsoberano.org.pdf](https://github.com/Automattic/newspack-theme/files/4596113/El.Soberano.-.No.JavaScript.-.La.plataforma.de.las.organizaciones.y.movimientos.socia_.-.elsoberano.org.pdf)
[TechNode — No JavaScript -- Latest China tech trends - technode.com.pdf](https://github.com/Automattic/newspack-theme/files/4596116/TechNode.No.JavaScript.--.Latest.China.tech.trends.-.technode.com.pdf)

**Comment by adekbadek** [comment]
Can't reproduce, issue is probably outdated.
