### ISSUE TITLE
IE11 Images compressed

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/newspack-theme#934]
**Describe the bug**
Images on the site ....

in-gl.de 

...when viewed on IE 11, are squeezed horizontally. 

Screenshot - https://d.pr/i/8OQTF4

I can see this viewing on browserstack too

**To Reproduce**
View the website on Window IE11

**Screenshots**
https://d.pr/i/8OQTF4

**Expected behavior**
The images not to be compressed

**Comment by laurelfulford** [comment]
Thanks for reporting this, @rickmgithub!

As this can be reproduced without any Newspack-related code, it's been reported here: https://github.com/ampproject/amphtml/issues/28398
