### ISSUE TITLE
Add breadcrumb trail

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-theme#94]
Look into adding breadcrumb trail to theme.

What would the path be for articles (Home > category > story?). First dig into how these are typically handled on news sites.

**Comment by claudiulodro** [comment]
[Yoast has a breadcrumb feature that will automatically handle the logic.](https://kb.yoast.com/kb/implement-wordpress-seo-breadcrumbs/) That's probably the easiest, and most standard way to go.

**Comment by akkiverma** [comment]
Yup, Yost breadcrumb works great. Check https://www.reviewcenter.in/ for example with newspack.

**Comment by claudiulodro** [comment]
The breadcrumbs look pretty good straight-out-of-the-box. 👍 Thanks for chiming in @akkiverma!

<img width="1286" alt="Screen Shot 2020-01-06 at 12 06 15 PM" src="https://user-images.githubusercontent.com/7317227/71845380-0cae0d80-307d-11ea-8553-18e6f336011c.png">

**Comment by thomasguillot** [comment]
Done. #855
