### ISSUE TITLE
More sharing links/engagement opportunities

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-theme#95]
Need to look into more social links and calls to action for sharing:

* Add links underneath the article as well, with a call to action text
* Is it possible to add links to blocks, like the pullquote block (or move to https://github.com/Automattic/newspack-blocks). 
* Investigate other possible locations (floating? May be best suited to the 'feature' stories)

**Comment by laurelfulford** [comment]
Second request, specifically for adding social sharing links also at the bottom of the page. 

Need to investigate what these controls should be like; right now we're using Jetpack's social share functionality, which has a toggle to show on a certain page type (post, page, archive, front page...) but no further nuance beyond that.

**Comment by sarahquigley** [comment]
I would very much like to see better more flexible social sharing support in Newspack. In addition to the current offering being quite inflexible, I've noted several issues recently:
https://github.com/Automattic/newspack-theme/issues/966
https://github.com/Automattic/newspack-theme/issues/965

**Comment by laurelfulford** [comment]
I'm going to close this issue for now; as we rework the theme to incorporate full site editing there should be more flexibility for things like this; in the short-term there hasn't been any movement on this in a while or recent requests.

**Comment by yogeshbeniwal** [comment]
@laurelfulford +1 for adding social more sharing features

- Have tried multiple plugins (both free and paid), too much functionality and configuration settings which deviates from core purpose and also doesn't support News Tagging
- Jetpack doesn't support all the popular social platforms
- For Engagement and Ux point of view, floating buttons on left side, closer to text will be better
