### ISSUE TITLE
Google Amp Ads going outside of content limits

### ISSUE THREAD

**Issue by mubashirist** [Automattic/newspack-theme#964]
**Describe the bug**
Hi,
I using Newspack Katharine theme on my website, i am using super cool ad inserter plugin and i have inserted the ad code as per your instructions on https://github.com/Automattic/newspack-theme/issues/620. like putting header spinet and placing ad code. but as you can see in screen shots below that ads are not following the theme they are totally out side of there. like ads are getting full width from left and right and getting over the right sidebar. Please fix this issue or guide me that how can i fix this. i have also attached snapshot of my ad code you can check that if there is any issue then let me know. I have contacted with the plugin author they said plugin is placing ads properly this issue is regarding theme

By the way on the phone ads looks perfect but on desktop it is having problem

Moreover is there any way to make/use adsense amp sticky ads with news. If yes please guide how?

Hope to hear from you soon

Kind regards,

Screenshots
![1](https://user-images.githubusercontent.com/66189392/83752805-8f65e380-a682-11ea-91fc-75eef7b95ce2.png)
![2](https://user-images.githubusercontent.com/66189392/83752813-912fa700-a682-11ea-8a74-b6b625317fc9.png)
![3](https://user-images.githubusercontent.com/66189392/83752818-9260d400-a682-11ea-8465-3244ed4f999e.png)
![4](https://user-images.githubusercontent.com/66189392/83752823-955bc480-a682-11ea-9158-4cf3e3674522.png)

**Expected behavior**
i am looking for ads to be shown within content limit

**Comment by laurelfulford** [comment]
Hi @mubashirist!

In your `amp-ad` code, it's being set to be the full width of the screen (it's the `width="100vw" part - it sets it to a percentage of the browser width). 

I admit I'm not an ads expert - most Newspack sites are handling ads through our Newspack and Newspack Ads plugins. 

For inserting `amp-ads` directly, [this post](https://sangams.com.np/how-to-make-adsense-work-with-amp-desktop-version/) might help in this case -- it suggests removing the width from the `amp-ad` code and setting a height based on the ad size you want to use.

I'm going to close this issue as it's not specific to the theme -- the ad is working as expected given the width that's been set in the code.
