### ISSUE TITLE
Figure out approach for single article dek text

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-theme#98]
Brought up in #76 by @jeffersonrabb: 

> Where is the dek text drawing from, and how can I get set up to view that?

![image](https://user-images.githubusercontent.com/177561/61009733-91b3a680-a328-11e9-884b-5190535d3beb.png)

This needs to be figured out. If we can turn the "post meta" (byline, date and shares) into a block, it can be a paragraph, with a paragraph style we set. If not, we might have to go a custom field route.

I've seen the Custom Excerpt used for something similar ([Twenty Sixteen](https://twentysixteendemo.wordpress.com) as an example), but that would show up on the homepage and archives, and the same content probably wouldn't make sense in the two different contexts.

**Comment by claudiulodro** [comment]
Related: https://github.com/Automattic/newspack-issues/issues/42

We need a way of inputting dek text that will display underneath the post title, [similar to the dek text on this article](https://hechingerreport.org/as-cities-dole-out-billions-in-subsidies-to-developers-teachers-ask-what-about-us/).

I have three ideas about what a good UI for this might look like until "post meta blocks" or "featured image blocks" get figured out in the future, but I'm very open to other ideas if anyone has them:
1. IMO the most natural place with the most accurate preview would be a new input underneath the title input for entering dek text. You could enter and see the text right under the title on the block editor. If you look at the screenshot below, it would be like the "Permalink" section, except under the title (I'm not sure whether it would have an Edit button, or just be editable always though).
2. An alternate approach if 1 ends up being super hacky or fragile is to have the input like the excerpt input in the sidebar, but with a live preview right under the title. You would enter text in the sidebar and it would render a non-editable preview under the title.
3. The worst-case (but still OK) approach would be to have text entered in the sidebar using an excerpt-like input with no preview in the block editor.

<img width="1505" alt="Screen Shot 2019-12-16 at 7 49 09 AM" src="https://user-images.githubusercontent.com/7317227/70921968-21493980-1fda-11ea-83c2-1f428250ecde.png">

**Important considerations:**
- The text should look nice with all style packs.
- The text should look nice with all featured image styles (default, small, beside feature image, etc.) and all templates (default, one-column, one-column wide)
