### ISSUE TITLE
Please Add Post Views Count 👁 on AMP Pages

### ISSUE THREAD

**Issue by SanjayKumarMonu** [Automattic/newspack-theme#984]
Hi Newspack Team,

Today, I request you guys to bring a new feature on the AMP Pages.

I am talking about **Post Views** that is used to display how many times a post or a page had been viewed in a reliable manner.

Jetpack has the stats feature in the backend to count how many times a post has been viewed. Is there a way to show the same post view count on each post on the amp pages in the front end via some sort of modification in the theme.

While looking for the solution, I found [**this post**](https://wordpress.org/support/topic/jetpack-statistics-on-amp-pages/) on the web but not able to understand, How it works and where to place it to enable the post view count on the front end.

Could you guys please consider this feature or help me out to display the post view count anywhere on my amp post pages at the front end?

With Best Regards,
Sanjay

**Comment by eduardogoncalves** [comment]
@SanjayKumarMonu in the [link you provided](https://wordpress.org/support/topic/jetpack-statistics-on-amp-pages/), they are talking about 'register' the pageviews. The AMP plugin already generate this code.
![image](https://user-images.githubusercontent.com/4308648/90179318-45ccff80-dd7b-11ea-80bc-5d1ec31ce1b7.png)

**Comment by laurelfulford** [comment]
Thanks for submitting this request, @SanjayKumarMonu! I think at this point we're unlikely to add view counts to the front-end.

There is a plugin -- [Post Views for Jetpack](https://wordpress.org/plugins/post-views-for-jetpack) -- that will show Jetpack post views on the front end. It uses a shortcode to display the post views `[jp_post_view]`, and has some options for how to incorporate that into sites under the FAQs.
